/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisPrincipais.painelClientes;

import com.mycompany.meunegocioprojetointegrador.bd.dominio.Cliente;
import com.mycompany.meunegocioprojetointegrador.bd.dominio.DadosDoCliente;
import com.mycompany.meunegocioprojetointegrador.view.Temas;
import com.mycompany.meunegocioprojetointegrador.view.controles.ControleClientes;
import com.mycompany.meunegocioprojetointegrador.view.controles.validador.EnunPesquisaClientes;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.GerenciadorDepaineis.INavegar;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.GerenciadorDepaineis.Painel;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.Rotas;
import com.mycompany.meunegocioprojetointegrador.view.paineis.Util.PainelLoadBarraCircular;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.ModeloComboboxPesquisaClientes;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.ModeloListaCOntatos;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.RencerCellCLiente;
import com.mycompany.meunegocioprojetointegrador.view.respostaParaView.RespostaDeLoad;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ramon
 */
public class PainelDeClientes extends Painel {
    private INavegar navegacao;
    private ControleClientes controle;
    /**
     * Creates new form PainelDeClientes
     */
    public PainelDeClientes(INavegar n,ControleClientes c) {
        navegacao=n;
        this.controle=c;
        initComponents();
        jCBTipoDePesquisa.setSelectedIndex(0);
        controle.getLista().observar((l)->{
            System.out.println("valor vindo da lista "+l);    
        ((ModeloListaCOntatos)jList1.getModel()).adicionarLista((List<DadosDoCliente>)l);
        }, this);
        
        controle.getEstadoLoad().observar((load)->{
         var animacao =(PainelLoadBarraCircular)jPAnimacao;   
         if(load instanceof RespostaDeLoad.Load){
         animacao.setVisible(true);
         return;
         }
         if(load instanceof RespostaDeLoad.Erro e){
         JOptionPane.showMessageDialog(this,e.mensagem());
         return;
         }
         animacao.setVisible(false);
        },this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel2 = new javax.swing.JPanel();
        jtPesquisa = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jCBTipoDePesquisa = new javax.swing.JComboBox<>();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jBPesquisar = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPAnimacao = new PainelLoadBarraCircular();
        jPanel3 = new javax.swing.JPanel();
        jBExcluir = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jBEditarCliente = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jBAdicionarNovoCliente = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jBPesquisarClientes = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        jTextField2.setText("jTextField2");

        setMaximumSize(new java.awt.Dimension(2147483647, 900));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setAlignmentX(CENTER_ALIGNMENT);
        jPanel1.setAlignmentY(CENTER_ALIGNMENT);
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(filler1);
        jPanel1.add(filler8);

        jPanel2.setAlignmentX(LEFT_ALIGNMENT);
        jPanel2.setAlignmentY(TOP_ALIGNMENT);
        jPanel2.setMaximumSize(new java.awt.Dimension(400, 60));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jtPesquisa.setMaximumSize(new java.awt.Dimension(200, 22));
        jtPesquisa.setMinimumSize(new java.awt.Dimension(200, 22));
        jtPesquisa.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel2.add(jtPesquisa);
        jPanel2.add(filler2);

        jCBTipoDePesquisa.setModel(new ModeloComboboxPesquisaClientes());
        jCBTipoDePesquisa.setMaximumSize(new java.awt.Dimension(100, 22));
        jCBTipoDePesquisa.setMinimumSize(new java.awt.Dimension(100, 22));
        jCBTipoDePesquisa.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel2.add(jCBTipoDePesquisa);
        jPanel2.add(filler10);

        jBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jBPesquisar.setMaximumSize(new java.awt.Dimension(23, 23));
        jBPesquisar.setMinimumSize(new java.awt.Dimension(23, 23));
        jBPesquisar.setBackground(Temas.backgraundBotoes);
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(jBPesquisar);
        jPanel2.add(filler9);

        jPAnimacao.setMaximumSize(new java.awt.Dimension(30, 30));
        jPAnimacao.setMinimumSize(new java.awt.Dimension(30, 30));
        jPAnimacao.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel2.add(jPAnimacao);

        jPanel1.add(jPanel2);

        jPanel3.setAlignmentX(LEFT_ALIGNMENT);
        jPanel3.setMaximumSize(new java.awt.Dimension(500, 60));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jBExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jBExcluir.setText("Excluir");
        jBExcluir.setMaximumSize(new java.awt.Dimension(102, 30));
        jBExcluir.setMinimumSize(new java.awt.Dimension(102, 30));
        jBExcluir.setPreferredSize(new java.awt.Dimension(102, 30));
        jBExcluir.setBackground(Temas.backgraundBotoes);
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(jBExcluir);
        jPanel3.add(filler3);

        jBEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jBEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jBEditarCliente.setBackground(Temas.backgraundBotoes);
        jBEditarCliente.setText("Editar");
        jBEditarCliente.setMaximumSize(new java.awt.Dimension(102, 30));
        jBEditarCliente.setMinimumSize(new java.awt.Dimension(102, 30));
        jBEditarCliente.setPreferredSize(new java.awt.Dimension(102, 30));
        jBEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarClienteActionPerformed(evt);
            }
        });
        jPanel3.add(jBEditarCliente);
        jPanel3.add(filler4);

        jBAdicionarNovoCliente.setBackground(Temas.backgraundBotoes);
        jBAdicionarNovoCliente.setForeground(new java.awt.Color(255, 255, 255));
        jBAdicionarNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jBAdicionarNovoCliente.setText("Adicionar");
        jBAdicionarNovoCliente.setMaximumSize(new java.awt.Dimension(102, 30));
        jBAdicionarNovoCliente.setMinimumSize(new java.awt.Dimension(102, 30));
        jBAdicionarNovoCliente.setPreferredSize(new java.awt.Dimension(102, 30));
        jBAdicionarNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarNovoClienteActionPerformed(evt);
            }
        });
        jPanel3.add(jBAdicionarNovoCliente);
        jPanel3.add(filler5);

        jBPesquisarClientes.setBackground(Temas.backgraundBotoes);
        jBPesquisarClientes.setForeground(new java.awt.Color(255, 255, 255));
        jBPesquisarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visibility_18dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jBPesquisarClientes.setText("Visualizar");
        jBPesquisarClientes.setMaximumSize(new java.awt.Dimension(102, 30));
        jBPesquisarClientes.setMinimumSize(new java.awt.Dimension(102, 30));
        jBPesquisarClientes.setPreferredSize(new java.awt.Dimension(102, 30));
        jBPesquisarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarClientesActionPerformed(evt);
            }
        });
        jPanel3.add(jBPesquisarClientes);

        jPanel1.add(jPanel3);
        jPanel1.add(filler6);

        jScrollPane1.setAlignmentX(LEFT_ALIGNMENT);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(800, 350));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(800, 350));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 350));

        jList1.setModel(new ModeloListaCOntatos());
        jList1.setCellRenderer(new RencerCellCLiente());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setToolTipText("");
        jList1.setAlignmentX(LEFT_ALIGNMENT);
        jList1.setMaximumSize(new java.awt.Dimension(365, 32767));
        jList1.setMinimumSize(new java.awt.Dimension(365, 32767));
        jList1.setPreferredSize(new java.awt.Dimension(365, 32767));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
       var item = jList1.getSelectedIndices();
       if(item.length>1){
       JOptionPane.showMessageDialog(jPanel3,"E nessesario selecionar apenas um item para exlucsao");
       return;
       }
       if(item.length<=0){
           JOptionPane.showMessageDialog(jPanel3,"Nenhum item foi selecionado");
           return;
       }
       var resposta =JOptionPane.showConfirmDialog(jPanel3,"Excluir um cliente tambem excluira todo o seu historico ","Obss :",JOptionPane.OK_CANCEL_OPTION);
       if(resposta!=JOptionPane.OK_OPTION){return;}
        
       controle.apagarCliente(((ModeloListaCOntatos)jList1.getModel()).getItemSelecionado(item[0]));
       
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBAdicionarNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarNovoClienteActionPerformed
        navegacao.navegar(new Rotas.AdicionarCliente(null));
    }//GEN-LAST:event_jBAdicionarNovoClienteActionPerformed

    private void jBEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarClienteActionPerformed
        var items=jList1.getSelectedIndices();
        if(items.length>1){avisoMuitosItemsSelecionados("editar");return;}
        if(items.length<1){avisoNenhumItemSelecionado("Edicao");return;}
        var itemselecionado=((ModeloListaCOntatos)jList1.getModel()).getItemSelecionado(items[0]);
        navegacao.navegar(new Rotas.AdicionarCliente(itemselecionado));
    }//GEN-LAST:event_jBEditarClienteActionPerformed

    private void jBPesquisarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarClientesActionPerformed
        var clicados=jList1.getSelectedIndices();
        if(clicados.length>1){avisoMuitosItemsSelecionados("visualizar ");return;}
        if(clicados.length<1){avisoNenhumItemSelecionado("visualizar");return;}
        var modelo =jList1.getSelectedValue();
        navegacao.navegar(new Rotas.VisualizarCliente(modelo));
    }//GEN-LAST:event_jBPesquisarClientesActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        var objetoSelecionado =(EnunPesquisaClientes) jCBTipoDePesquisa.getSelectedItem();
        if(objetoSelecionado==null) {
           JOptionPane.showMessageDialog(this,"Nenuma Opcao De Pesquisa Selecionada");
           return;
        }
        controle.pesquisar(jtPesquisa.getText(),objetoSelecionado );
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void avisoMuitosItemsSelecionados(String acao){
        JOptionPane.showMessageDialog(this,"E nesesario selecionar apenas um item para "+acao,"Observacao",JOptionPane.INFORMATION_MESSAGE);
               
    }
    
    private void avisoNenhumItemSelecionado(String acao){
    JOptionPane.showMessageDialog(this,"Nenhum item selecionado para "+acao);
    }

    @Override
    public void iniciar() {
        super.iniciar(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        System.out.println("painel cliente iniciado caregando lista");
        controle.caregarListaInicial();
    }

    @Override
    public void finalizar() {
        super.finalizar(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        controle.finalizar();
        controle =null;
        navegacao=null;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jBAdicionarNovoCliente;
    private javax.swing.JButton jBEditarCliente;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBPesquisarClientes;
    private javax.swing.JComboBox<EnunPesquisaClientes> jCBTipoDePesquisa;
    private javax.swing.JList<DadosDoCliente> jList1;
    private javax.swing.JPanel jPAnimacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jtPesquisa;
    // End of variables declaration//GEN-END:variables
}
