/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisDeAdicao.painelAdicaoProdutos;

import com.mycompany.meunegocioprojetointegrador.bd.dominio.ProdutoServico;
import com.mycompany.meunegocioprojetointegrador.view.Temas;
import com.mycompany.meunegocioprojetointegrador.view.controles.ControleAdicionarProdutos;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.GerenciadorDepaineis.INavegar;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.GerenciadorDepaineis.Painel;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.Rotas;
import com.mycompany.meunegocioprojetointegrador.view.paineis.Util.Interuptor;
import com.mycompany.meunegocioprojetointegrador.view.paineis.Util.PainelLoadBarraCircular;
import com.mycompany.meunegocioprojetointegrador.view.respostaParaView.RespostaDeLoad;
import javax.swing.JOptionPane;

/**
 *
 * @author ramon
 */
public class PainelAdicionarProdutos extends Painel {
    
    private INavegar navegar;
    private ControleAdicionarProdutos controle;
    /**
     * Creates new form AdicionarProdutos
     */
    public PainelAdicionarProdutos(ControleAdicionarProdutos controle,INavegar n) {
        initComponents();
        this.controle=controle;
        navegar=n;
        animacao.setVisible(false);
        
        controle.getEstadoProdutoServico().observar((p)->{
            if(p!=null){ updateDados((ProdutoServico) p);}
           
        },this);
        controle.getEstadoDeSalvamento().observar((est)->{
        if(est instanceof RespostaDeLoad.Load ){
        animacao.setVisible(true);
            System.err.println("Animavao deve comesar  ...");
        }
        if(est instanceof RespostaDeLoad.Erro e){
         animacao.setVisible(false);
            mensagemDeErro(e.mensagem());
        }
        if(est instanceof RespostaDeLoad.ErroVasio ){
            animacao.setVisible(false);
            mensagemDeErro("Ouve um erro desconhesido");
        }
        if(est instanceof RespostaDeLoad.OK || est instanceof RespostaDeLoad.OKVasio){
         animacao.setVisible(false);
            navegar.navegar(null);
        }
        }, this);
        
    }
    private void mensagemDeErro(String s){
        JOptionPane.showMessageDialog(this,s , "Atencao :",JOptionPane.INFORMATION_MESSAGE);
    }
    private void updateDados(ProdutoServico ps){
        if(ps!=null){
         System.err.println("adicionando os dados pasados "+ps);
        txNome.setText(ps.getNome());
        txDescricao.setText(ps.getDescricao());
        txPreco.setText(String.format("%.2f",ps.getPreco()));
        var interuptor =(Interuptor)jInterupto;
        interuptor.setSelecao(ps.isServico());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txNome = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txPreco = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txDescricao = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jInterupto = new Interuptor();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        animacao = new PainelLoadBarraCircular();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton2 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 900));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setRequestFocusEnabled(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setAlignmentX(CENTER_ALIGNMENT);
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(filler1);

        jPanel3.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel3.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setText("Nome");
        jPanel3.add(jLabel2);

        txNome.setAlignmentX(LEFT_ALIGNMENT);
        txNome.setMaximumSize(new java.awt.Dimension(500, 22));
        txNome.setMinimumSize(new java.awt.Dimension(500, 22));
        txNome.setName(""); // NOI18N
        txNome.setPreferredSize(new java.awt.Dimension(500, 22));
        txNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeActionPerformed(evt);
            }
        });
        jPanel3.add(txNome);

        jPanel1.add(jPanel3);

        jPanel4.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel4.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel4.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setText("Preço");
        jPanel4.add(jLabel3);

        txPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txPreco.setAlignmentX(0.0F);
        txPreco.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        txPreco.setMinimumSize(new java.awt.Dimension(2147483647, 22));
        txPreco.setPreferredSize(new java.awt.Dimension(2147483647, 22));
        jPanel4.add(txPreco);

        jPanel1.add(jPanel4);

        jPanel5.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel5.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel5.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setText("Descricao");
        jPanel5.add(jLabel4);

        txDescricao.setAlignmentX(LEFT_ALIGNMENT);
        txDescricao.setMaximumSize(new java.awt.Dimension(500, 22));
        txDescricao.setMinimumSize(new java.awt.Dimension(500, 22));
        txDescricao.setName(""); // NOI18N
        txDescricao.setPreferredSize(new java.awt.Dimension(250, 22));
        jPanel5.add(txDescricao);

        jPanel1.add(jPanel5);

        jPanel6.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel6.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel6.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel6.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setText("Produto/Serviço");
        jPanel6.add(jLabel5);

        jInterupto.setBackground(new java.awt.Color(255, 255, 255));
        jInterupto.setAlignmentX(LEFT_ALIGNMENT);
        jInterupto.setMaximumSize(new java.awt.Dimension(100, 20));
        jInterupto.setMinimumSize(new java.awt.Dimension(100, 20));
        jInterupto.setOpaque(false);

        javax.swing.GroupLayout jInteruptoLayout = new javax.swing.GroupLayout(jInterupto);
        jInterupto.setLayout(jInteruptoLayout);
        jInteruptoLayout.setHorizontalGroup(
            jInteruptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jInteruptoLayout.setVerticalGroup(
            jInteruptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel6.add(jInterupto);

        jPanel1.add(jPanel6);

        jPanel7.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel7.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel7.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel7.setRequestFocusEnabled(false);
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));

        jButton1.setBackground(Temas.backgraundBotoes);
        jButton1.setForeground(Temas.foregraundBotoes);
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);
        jPanel7.add(filler3);

        animacao.setMaximumSize(new java.awt.Dimension(50, 50));
        animacao.setMinimumSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout animacaoLayout = new javax.swing.GroupLayout(animacao);
        animacao.setLayout(animacaoLayout);
        animacaoLayout.setHorizontalGroup(
            animacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        animacaoLayout.setVerticalGroup(
            animacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel7.add(animacao);
        jPanel7.add(filler4);

        jButton2.setBackground(Temas.backgraundBotoes);
        jButton2.setForeground(Temas.foregraundBotoes);
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        jPanel1.add(jPanel7);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void txNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        navegar.navegar(new Rotas.Produtos());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
             controle.operacaoDeSalvar(txNome.getText(), 
                                   txDescricao.getText(),
                                       txPreco.getText() ,
                                       ((Interuptor)jInterupto).isClicadao());
     
    }//GEN-LAST:event_jButton2ActionPerformed

    @Override
    public void iniciar() {
        super.iniciar(); }

    @Override
    public void finalizar() {
        super.finalizar(); 
        controle.finalizar();
        controle=null;
        navegar=null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel animacao;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jInterupto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txDescricao;
    private javax.swing.JTextField txNome;
    private javax.swing.JFormattedTextField txPreco;
    // End of variables declaration//GEN-END:variables
}
