/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisDeVisualizacao.painelVisualizarClientes;

import com.mycompany.meunegocioprojetointegrador.bd.dominio.Cliente;
import com.mycompany.meunegocioprojetointegrador.bd.dominio.DadosDoCliente;
import com.mycompany.meunegocioprojetointegrador.bd.dominio.Endereco;
import com.mycompany.meunegocioprojetointegrador.bd.dominio.Telefone;
import com.mycompany.meunegocioprojetointegrador.view.Temas;
import com.mycompany.meunegocioprojetointegrador.view.controles.ControleVisualizarClientes;
import com.mycompany.meunegocioprojetointegrador.view.paineis.Util.util.PainelComBorda;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.GerenciadorDepaineis.Painel;
import java.awt.CardLayout;
import java.util.List;

/**
 *
 * @author ramon
 */
public class PainelVisualizarCliente extends Painel {
    private ControleVisualizarClientes controle;
    private Runnable voutar;
    private PainelListaDeTelefoenes telefones;
    private SubEstadosDeClientes estadoDalista=new SubEstadosDeClientes.Telefone();
    private PainelEndereco enderecos=new PainelEndereco();
    private Editar editar;
    /**
     * Creates new form PianeVisualizarCliente
     */
    public PainelVisualizarCliente(ControleVisualizarClientes c,Runnable vouta,Editar e) {
        this.voutar=vouta;
        this.controle=c;
        editar=e;
        initComponents();
        telefones= new PainelListaDeTelefoenes();
        jpListas.add(telefones,SubEstadosDeClientes.Telefone.class.getSimpleName());
        jpListas.add(enderecos,SubEstadosDeClientes.Endereco.class.getSimpleName());
        iniciarDados();
        ((CardLayout) jpListas.getLayout()).show(jpListas, estadoDalista.getClass().getSimpleName());
        controle.getEstadoListaEnderecos().observar((valor)->{
        enderecos.updateLista((List<Endereco>) valor);
        },this);
        controle.getEstadoListaTelefones().observar((valor)->{telefones.updateList((List<Telefone>) valor);},this);
        
        
    }

    private void iniciarDados(){
    controle.getEstadoCliente().observar((dados)->{
    var cliente=(Cliente)dados;    
    this.jlNome.setText(cliente.getNome());
    String cpf=(cliente.getCpf()==null||cliente.getCpf().isBlank())?"Não informado":cliente.getCpf();
    String cnpj=(cliente.getCnpj()==null||cliente.getCnpj().isBlank())?"Não informado":cliente.getCnpj();
    this.jlCpf.setText(cpf);
    this.jlCnpj.setText(cnpj);
    
    },this);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel1 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(32767, 50), new java.awt.Dimension(32767, 50), new java.awt.Dimension(32767, 50));
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jlNome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 10), new java.awt.Dimension(30, 10), new java.awt.Dimension(30, 10));
        jlCnpj = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 10), new java.awt.Dimension(30, 10), new java.awt.Dimension(30, 10));
        jlCpf = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton2 = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton1 = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jpListas = new PainelComBorda();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton4 = new javax.swing.JButton();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));

        setMaximumSize(new java.awt.Dimension(32767, 900));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(filler2);

        jPanel2.setMaximumSize(new java.awt.Dimension(600, 50));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cliente :");
        jPanel2.add(jLabel1);
        jPanel2.add(filler3);

        jlNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlNome.setText("jLabel2");
        jlNome.setMaximumSize(new java.awt.Dimension(500, 25));
        jPanel2.add(jlNome);

        jPanel1.add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(600, 50));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cnpj :");
        jPanel3.add(jLabel3);
        jPanel3.add(filler4);

        jlCnpj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlCnpj.setText("jLabel2");
        jlCnpj.setMaximumSize(new java.awt.Dimension(500, 25));
        jPanel3.add(jlCnpj);

        jPanel1.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(600, 50));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Cpf :");
        jLabel5.setMaximumSize(new java.awt.Dimension(45, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(45, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(45, 25));
        jPanel4.add(jLabel5);
        jPanel4.add(filler5);

        jlCpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlCpf.setText("jLabel2");
        jlCpf.setMaximumSize(new java.awt.Dimension(500, 25));
        jPanel4.add(jlCpf);

        jPanel1.add(jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(600, 50));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));
        jPanel5.add(filler7);

        jButton2.setText("Telefone");
        jButton2.setBackground(Temas.backgraundBotoes);
        jButton2.setForeground(Temas.foregraundBotoes);
        jButton2.setMaximumSize(new java.awt.Dimension(102, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(102, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jPanel5.add(filler6);

        jButton1.setText("Endereço");
        jButton1.setBackground(Temas.backgraundBotoes);
        jButton1.setForeground(Temas.foregraundBotoes);
        jButton1.setMaximumSize(new java.awt.Dimension(102, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(102, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jPanel5.add(filler8);

        jPanel1.add(jPanel5);

        jpListas.setMaximumSize(new java.awt.Dimension(600, 200));
        jpListas.setMinimumSize(new java.awt.Dimension(600, 200));
        jpListas.setLayout(new java.awt.CardLayout());
        jPanel1.add(jpListas);

        jPanel7.setMaximumSize(new java.awt.Dimension(600, 50));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow_back_23dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton3.setText("Voutar");
        jButton3.setBackground(Temas.backgraundBotoes);
        jButton3.setForeground(Temas.foregraundBotoes);
        jButton3.setMaximumSize(new java.awt.Dimension(102, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(102, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);
        jPanel7.add(filler10);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jButton4.setText("Editar");
        jButton4.setBackground(Temas.backgraundBotoes);
        jButton4.setForeground(Temas.foregraundBotoes);
        jButton4.setMaximumSize(new java.awt.Dimension(102, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(102, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);
        jPanel7.add(filler11);

        jPanel1.add(jPanel7);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        voutar.run();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(estadoDalista instanceof SubEstadosDeClientes.Telefone){
        var prosimo=estadoDalista.prosimo();
       ((CardLayout) jpListas.getLayout()).show(jpListas, prosimo.getClass().getSimpleName());
       estadoDalista=prosimo; 
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(estadoDalista instanceof SubEstadosDeClientes.Endereco){
        var prosimo=estadoDalista.prosimo();
       ((CardLayout) jpListas.getLayout()).show(jpListas, prosimo.getClass().getSimpleName());
       estadoDalista=prosimo; }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        editar.editar(controle.getDadosDoCliente());
    }//GEN-LAST:event_jButton4ActionPerformed
    
    @Override
    public void finalizar() {
        super.finalizar(); 
        this.voutar=null;
        this.telefones=null;
        controle.finalizar();
        controle=null;
    }

    @Override
    public void iniciar() {
       super.iniciar(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
       var idCliente=controle.getEstadoCliente().getValot();
       controle.ListarEnderecos(idCliente.getId());
       controle.ListarTelefones(idCliente.getId());
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jlCnpj;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlNome;
    private javax.swing.JPanel jpListas;
    // End of variables declaration//GEN-END:variables

public interface Editar{
public void editar(DadosDoCliente d);
}


}
