/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisDeVisualizacao.painelVisualizarClientes;

import com.mycompany.meunegocioprojetointegrador.bd.dominio.Endereco;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.ModeloDeListaEnderecos;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.RenderCelEndereco;
import java.util.List;
import javax.swing.UIManager;

/**
 *
 * @author ramon
 */
public class PainelEndereco extends javax.swing.JPanel {

    /**
     * Creates new form PainelEndereco
     */
    public PainelEndereco() {
        initComponents();
        jList1.setBackground(UIManager.getColor("Painel.background"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jList1.setModel(new ModeloDeListaEnderecos());
        jList1.setCellRenderer(new RenderCelEndereco());
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    public void updateLista(List<Endereco> l){
    ((ModeloDeListaEnderecos)jList1.getModel()).adicionarLista(l);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Endereco> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
