/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisPrincipais.painelProdutos;

import com.mycompany.meunegocioprojetointegrador.bd.dominio.ProdutoServico;
import com.mycompany.meunegocioprojetointegrador.view.Temas;
import com.mycompany.meunegocioprojetointegrador.view.controles.ControleProdutos;
import com.mycompany.meunegocioprojetointegrador.view.controles.validador.EnumPesquisaProdutos;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.GerenciadorDepaineis.INavegar;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.GerenciadorDepaineis.Painel;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.Rotas;
import com.mycompany.meunegocioprojetointegrador.view.paineis.Util.PainelLoadBarraCircular;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.ModeloComboBoxPesquisaProdutos;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.ModeloTabelaProdutos;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.RenderCelTabelaPRoduto;
import com.mycompany.meunegocioprojetointegrador.view.respostaParaView.RespostaDeLoad;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ramon
 */
public class PainelProdutos extends Painel {
    private INavegar navegar;
    private ControleProdutos controle;
    /**
     * Creates new form PainelRequisicoes
     */
    public PainelProdutos(ControleProdutos c,INavegar n) {
        controle=c;
        navegar=n;
        initComponents();
        jCBTipoDePesquisa.setSelectedIndex(0);
        c.getEstadoDaLista().observar((l)->{
        ((ModeloTabelaProdutos)jTable1.getModel()).updateLista((List<ProdutoServico>) l);
        }, this);
        c.getEstadoLoadLista().observar((load)->{
         if(load instanceof RespostaDeLoad.Load){
         jPAnimacao.setVisible(true);
         return;
         }
         if(load instanceof RespostaDeLoad.Erro e){
         jPAnimacao.setVisible(false);    
         JOptionPane.showMessageDialog(this,e.mensagem());
         return;
         }
         jPAnimacao.setVisible(false);
         
        }, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel2 = new javax.swing.JPanel();
        jTPesquisa = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jCBTipoDePesquisa = new javax.swing.JComboBox<>();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jBPesquisar = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPAnimacao = new PainelLoadBarraCircular();
        jPanel3 = new javax.swing.JPanel();
        jBEditarProduto = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jBAdicionarNovoProduto = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jBVisualizarProduto = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));

        setAlignmentX(CENTER_ALIGNMENT);
        setAlignmentY(CENTER_ALIGNMENT);
        setMaximumSize(new java.awt.Dimension(32767, 900));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setRequestFocusEnabled(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setAlignmentX(CENTER_ALIGNMENT);
        jPanel1.setAlignmentY(CENTER_ALIGNMENT);
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(filler2);

        jPanel2.setAlignmentX(LEFT_ALIGNMENT);
        jPanel2.setMaximumSize(new java.awt.Dimension(600, 60));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 60));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTPesquisa.setMaximumSize(new java.awt.Dimension(200, 22));
        jTPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPesquisaActionPerformed(evt);
            }
        });
        jPanel2.add(jTPesquisa);
        jPanel2.add(filler3);

        jCBTipoDePesquisa.setModel(new ModeloComboBoxPesquisaProdutos());
        jCBTipoDePesquisa.setMaximumSize(new java.awt.Dimension(100, 22));
        jPanel2.add(jCBTipoDePesquisa);
        jPanel2.add(filler4);

        jBPesquisar.setBackground(Temas.backgraundBotoes);
        jBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jBPesquisar.setMaximumSize(new java.awt.Dimension(23, 23));
        jBPesquisar.setMinimumSize(new java.awt.Dimension(23, 23));
        jBPesquisar.setOpaque(true);
        jBPesquisar.setPreferredSize(new java.awt.Dimension(23, 23));
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(jBPesquisar);
        jPanel2.add(filler9);

        jPAnimacao.setMaximumSize(new java.awt.Dimension(23, 23));
        jPAnimacao.setMinimumSize(new java.awt.Dimension(23, 23));
        jPAnimacao.setName(""); // NOI18N
        jPAnimacao.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel2.add(jPAnimacao);

        jPanel1.add(jPanel2);

        jPanel3.setAlignmentX(LEFT_ALIGNMENT);
        jPanel3.setMaximumSize(new java.awt.Dimension(500, 60));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jBEditarProduto.setBackground(Temas.backgraundBotoes);
        jBEditarProduto.setForeground(new java.awt.Color(255, 255, 255));
        jBEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jBEditarProduto.setText("Editar");
        jBEditarProduto.setMaximumSize(new java.awt.Dimension(102, 30));
        jBEditarProduto.setMinimumSize(new java.awt.Dimension(102, 30));
        jBEditarProduto.setPreferredSize(new java.awt.Dimension(102, 30));
        jBEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(jBEditarProduto);
        jPanel3.add(filler6);

        jBAdicionarNovoProduto.setBackground(Temas.backgraundBotoes);
        jBAdicionarNovoProduto.setForeground(new java.awt.Color(255, 255, 255));
        jBAdicionarNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jBAdicionarNovoProduto.setText("Adicionar");
        jBAdicionarNovoProduto.setMaximumSize(new java.awt.Dimension(102, 30));
        jBAdicionarNovoProduto.setMinimumSize(new java.awt.Dimension(102, 30));
        jBAdicionarNovoProduto.setPreferredSize(new java.awt.Dimension(102, 30));
        jBAdicionarNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarNovoProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(jBAdicionarNovoProduto);
        jPanel3.add(filler7);

        jBVisualizarProduto.setBackground(Temas.backgraundBotoes);
        jBVisualizarProduto.setForeground(new java.awt.Color(255, 255, 255));
        jBVisualizarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visibility_18dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jBVisualizarProduto.setText("Visualizar");
        jBVisualizarProduto.setMaximumSize(new java.awt.Dimension(110, 30));
        jBVisualizarProduto.setMinimumSize(new java.awt.Dimension(110, 30));
        jBVisualizarProduto.setPreferredSize(new java.awt.Dimension(110, 30));
        jBVisualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVisualizarProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(jBVisualizarProduto);

        jPanel1.add(jPanel3);
        jPanel1.add(filler8);

        jScrollPane1.setAlignmentX(LEFT_ALIGNMENT);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(700, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 400));

        jTable1.setModel(new ModeloTabelaProdutos());
        jTable1.setSelectionBackground(java.awt.Color.darkGray);
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        var header=jTable1.getTableHeader();
        header.setDefaultRenderer(new RenderCelTabelaPRoduto());
        var columModel=jTable1.getColumnModel();
        columModel.getColumn(0).setMaxWidth(50);
        columModel.getColumn(1).setMaxWidth(400);
        columModel.getColumn(2).setMaxWidth(100);
        columModel.getColumn(3).setMaxWidth(80);
        columModel.getColumn(4).setMaxWidth(80);
        jTable1.setAutoCreateColumnsFromModel(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);

        add(jPanel1);
        add(filler1);
    }// </editor-fold>//GEN-END:initComponents

    private void jTPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPesquisaActionPerformed

    private void jBAdicionarNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarNovoProdutoActionPerformed
        navegar.navegar(new Rotas.AdicionarProduto(null));
    }//GEN-LAST:event_jBAdicionarNovoProdutoActionPerformed

    private void jBEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarProdutoActionPerformed
       var selecao=jTable1.getSelectedRows();
       if(selecao.length>1){avisoEdicaoMuintosSelecionados();return;}
       if(selecao.length<1){avisoEdicaoNenhumItemSelecionado();return;}
       var modeloDaTabela=(ModeloTabelaProdutos)jTable1.getModel();
       var modelo=modeloDaTabela.getSelecao(selecao[0]);
        System.out.println("produto selecionado "+modelo);
       navegar.navegar(new Rotas.AdicionarProduto(modelo));
    }//GEN-LAST:event_jBEditarProdutoActionPerformed

    private void jBVisualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVisualizarProdutoActionPerformed
       var selecionados=jTable1.getSelectedRows();
       if(selecionados.length>1){avisoEdicaoMuintosSelecionados();return;}
       if(selecionados.length<1){avisoEdicaoNenhumItemSelecionado();return;}
       var items=((ModeloTabelaProdutos)jTable1.getModel()).getSelecao(selecionados[0]);
       navegar.navegar(new Rotas.VisualizarProdutoServico(items));
    }//GEN-LAST:event_jBVisualizarProdutoActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        var opcao=(EnumPesquisaProdutos)jCBTipoDePesquisa.getSelectedItem();
        if(opcao==null){
        JOptionPane.showMessageDialog(this,"Nenhuma opcao de pesquisa foi selecionada");
        return;
        }
        controle.pesquisar(opcao,jTPesquisa.getText());
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void avisoEdicaoMuintosSelecionados(){
        JOptionPane.showMessageDialog(this,"Para realizar a operacao e nesesario selecionar apenas um item da tabela","Observaçao",JOptionPane.INFORMATION_MESSAGE);
    }
    private void avisoEdicaoNenhumItemSelecionado(){
           JOptionPane.showMessageDialog(this,"Para realizar a operacao e nesesario selecionar  um item da tabela","Observaçao",JOptionPane.INFORMATION_MESSAGE);
    
    }

    @Override
    public void iniciar() {
        super.iniciar();
        controle.caregarListaInicial();
    }

    @Override
    public void finalizar() {
        super.finalizar();
        controle.finalizar();
        controle=null;
        navegar=null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jBAdicionarNovoProduto;
    private javax.swing.JButton jBEditarProduto;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBVisualizarProduto;
    private javax.swing.JComboBox<EnumPesquisaProdutos> jCBTipoDePesquisa;
    private javax.swing.JPanel jPAnimacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTPesquisa;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
