/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisDeAdicao.paineisAdicaoDeCLientes;

import com.mycompany.meunegocioprojetointegrador.bd.dominio.Cliente;
import com.mycompany.meunegocioprojetointegrador.view.IFinalizar;
import com.mycompany.meunegocioprojetointegrador.view.Temas;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.GerenciadorDepaineis.INavegar;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.Rotas;
import com.mycompany.meunegocioprojetointegrador.view.respostaParaView.RespostaDeValidacaoDeDados;
import javax.swing.JOptionPane;

/**
 *
 * @author ramon
 */
public class PainelDadosDocliente extends javax.swing.JPanel implements IFinalizar{
    
    private InterfaceNavegacaoENtreEstagios navegarProsimo;
    private INavegar cancelar;
    private Runnable validar;
    private Cliente cliente =null;
    /**
     * Creates new form PainelDadosDocliente
     */
    public PainelDadosDocliente(InterfaceNavegacaoENtreEstagios n,INavegar c,Runnable validar) {
        cancelar=c;
        navegarProsimo=n;
        this.validar=validar;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jLabel2 = new javax.swing.JLabel();
        txNome = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txCpf = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txCnpj = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jbCancelar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jbProximo = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setAlignmentX(CENTER_ALIGNMENT);
        jPanel2.setMaximumSize(new java.awt.Dimension(500, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 100));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel3.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jPanel3.add(filler1);

        jLabel2.setText("Nome");
        jPanel3.add(jLabel2);

        txNome.setAlignmentX(LEFT_ALIGNMENT);
        txNome.setMaximumSize(new java.awt.Dimension(500, 22));
        txNome.setMinimumSize(new java.awt.Dimension(500, 22));
        txNome.setName(""); // NOI18N
        txNome.setPreferredSize(new java.awt.Dimension(500, 22));
        txNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeActionPerformed(evt);
            }
        });
        jPanel3.add(txNome);

        jPanel2.add(jPanel3);

        jPanel4.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel4.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel4.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setText("CPF");
        jPanel4.add(jLabel3);

        try {
            txCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txCpf.setAlignmentX(0.0F);
        txCpf.setMaximumSize(new java.awt.Dimension(500, 22));
        txCpf.setMinimumSize(new java.awt.Dimension(500, 22));
        txCpf.setPreferredSize(new java.awt.Dimension(500, 22));
        jPanel4.add(txCpf);

        jPanel2.add(jPanel4);

        jPanel5.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel5.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel5.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setText("CNPJ");
        jPanel5.add(jLabel4);

        try {
            txCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txCnpj.setAlignmentX(0.0F);
        txCnpj.setMaximumSize(new java.awt.Dimension(500, 22));
        txCnpj.setMinimumSize(new java.awt.Dimension(500, 22));
        txCnpj.setPreferredSize(new java.awt.Dimension(500, 22));
        jPanel5.add(txCnpj);

        jPanel2.add(jPanel5);

        jPanel7.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel7.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel7.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel7.setRequestFocusEnabled(false);
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));

        jbCancelar.setBackground(Temas.backgraundBotoes);
        jbCancelar.setForeground(Temas.foregraundBotoes);
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel7.add(jbCancelar);
        jPanel7.add(filler2);

        jbProximo.setBackground(Temas.backgraundBotoes);
        jbProximo.setForeground(Temas.foregraundBotoes);
        jbProximo.setText("Proximo");
        jbProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProximoActionPerformed(evt);
            }
        });
        jPanel7.add(jbProximo);

        jPanel2.add(jPanel7);
        jPanel2.add(filler3);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void txNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomeActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
    cancelar.navegar(new Rotas.Clientes());
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProximoActionPerformed
        validar.run();
    }//GEN-LAST:event_jbProximoActionPerformed

    public void respsotaInvalidacao(RespostaDeValidacaoDeDados r){
    if(r instanceof RespostaDeValidacaoDeDados.Invalido i){
        JOptionPane.showMessageDialog(jPanel1,i.mensagem());
        
    }
    if(r instanceof RespostaDeValidacaoDeDados.Validado v){
    if(cliente==null)cliente= new Cliente(null,getCpf(),getCnpj(), getNome());
    else{
    var stringcpf= getCpf().replaceAll("\\D", "");
    var stringcnpj=getCnpj().replaceAll("\\D", "");
    
    cliente.setCnpj((stringcnpj.isBlank())? "" : getCnpj());
    cliente.setCpf((stringcpf.isBlank())?"":getCpf());
    cliente.setNome(getNome());
    }
    navegarProsimo.navegue();
    }
    }
    public Cliente getCliente(){
    return cliente;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbProximo;
    private javax.swing.JFormattedTextField txCnpj;
    private javax.swing.JFormattedTextField txCpf;
    private javax.swing.JTextField txNome;
    // End of variables declaration//GEN-END:variables

    
    public void updateDados(Cliente c){
    if(c!=null){
    this.txNome.setText(c.getNome());
    this.txCpf.setText(c.getCpf());
    this.txCnpj.setText(c.getCnpj());
    cliente=c;}    
    
    }
    
    public String getNome (){
    return txNome.getText();
    }
    public String getCpf(){
    return txCpf.getText();
    }
    public String getCnpj(){
    return txCnpj.getText();
    }
    @Override
    public void finalizar() {
       cancelar=null;
       navegarProsimo=null;
       cliente=null;
       validar=null; 
    }
}
