/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisDeAdicao.paineisAdicaoDeCLientes;

import com.mycompany.meunegocioprojetointegrador.bd.dominio.Telefone;
import com.mycompany.meunegocioprojetointegrador.view.IFinalizar;
import com.mycompany.meunegocioprojetointegrador.view.Temas;
import com.mycompany.meunegocioprojetointegrador.view.paineis.Util.PainelLoadBarraCircular;
import com.mycompany.meunegocioprojetointegrador.view.respostaParaView.RespostaDeValidacaoDeDados;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ramon
 */
public class PainelTelefone extends javax.swing.JPanel implements IFinalizar{
    private InterfaceNavegacaoENtreEstagios anterio;
    private Runnable salvar;
    private Runnable validar;
    private int indice =0;
    private List<Telefone> telefones = new ArrayList<>();
    private RespostaDeValidacaoDeDados r = new RespostaDeValidacaoDeDados.NaoAvaliado();
    /**
     * Creates new form PainelDadosDocliente
     */
    public PainelTelefone(InterfaceNavegacaoENtreEstagios n,Runnable salvar,Runnable validar) {
        anterio=n;
        this.validar=validar;
        this.salvar=salvar;
        initComponents();
        animacao.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jLabel2 = new javax.swing.JLabel();
        txTelefone = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jbVoultar = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        animacao = new PainelLoadBarraCircular();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        botaoSalvar = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setAlignmentX(CENTER_ALIGNMENT);
        jPanel2.setMaximumSize(new java.awt.Dimension(500, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 100));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel3.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jPanel3.add(filler1);

        jLabel2.setText("Telefone");
        jPanel3.add(jLabel2);

        try {
            txTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txTelefone.setMaximumSize(new java.awt.Dimension(500, 22));
        txTelefone.setMinimumSize(new java.awt.Dimension(500, 22));
        txTelefone.setPreferredSize(new java.awt.Dimension(500, 22));
        jPanel3.add(txTelefone);

        jPanel2.add(jPanel3);

        jPanel7.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel7.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel7.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel7.setRequestFocusEnabled(false);
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));

        jbVoultar.setBackground(Temas.backgraundBotoes);
        jbVoultar.setForeground(Temas.foregraundBotoes);
        jbVoultar.setText("Voultar");
        jbVoultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoultarActionPerformed(evt);
            }
        });
        jPanel7.add(jbVoultar);
        jPanel7.add(filler4);

        animacao.setMaximumSize(new java.awt.Dimension(50, 50));
        animacao.setMinimumSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout animacaoLayout = new javax.swing.GroupLayout(animacao);
        animacao.setLayout(animacaoLayout);
        animacaoLayout.setHorizontalGroup(
            animacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        animacaoLayout.setVerticalGroup(
            animacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel7.add(animacao);
        jPanel7.add(filler5);

        botaoSalvar.setBackground(Temas.backgraundBotoes);
        botaoSalvar.setForeground(Temas.foregraundBotoes);
        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });
        jPanel7.add(botaoSalvar);

        jPanel2.add(jPanel7);
        jPanel2.add(filler3);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void jbVoultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoultarActionPerformed
        if(indice>0){
         indice--;
         updateTelefone(telefones.get(indice));
         if(indice<telefones.size()-1)botaoSalvar.setText("Proximo");
         else botaoSalvar.setText("Salvar");
         return;
        }
        anterio.navegue();
    }//GEN-LAST:event_jbVoultarActionPerformed

    private boolean avisoAdicionarMaisUmContato(){
    var respsota =JOptionPane.showInternalConfirmDialog(jPanel1,"Voce deseja adicionar mais um Telefone","Obs:" ,JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null);
    
    if(respsota==JOptionPane.OK_OPTION)return true;
    return false;
    }
    
    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
      validar.run();
    }//GEN-LAST:event_botaoSalvarActionPerformed
    
    public List<Telefone> getLista(){
    return telefones;
    }

    public void avisoAnimar(){
    animacao.setVisible(true);
    }
    public void avisoPararAnimacao(){
    animacao.setVisible(false);
    }
    public void avisoDeErro(String s){
    JOptionPane.showMessageDialog(jPanel1, s);
    }
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel animacao;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jbVoultar;
    private javax.swing.JFormattedTextField txTelefone;
    // End of variables declaration//GEN-END:variables
    
    public void respostaDeValidacao(RespostaDeValidacaoDeDados r){
    if(r instanceof RespostaDeValidacaoDeDados.Invalido i){
     JOptionPane.showMessageDialog(jPanel1,i.mensagem(),"Campo invalido",JOptionPane.INFORMATION_MESSAGE);
     return;
    }
    if(r instanceof RespostaDeValidacaoDeDados.Validado){
        System.out.println("Validaco ocoreu com suceso");
        
     var telefone = new Telefone(null,null,txTelefone.getText());
      if(indice==telefones.size()){
       telefones.add(telefone);
       indice++;
       
       var respsota =avisoAdicionarMaisUmContato();
       if(respsota){txTelefone.setText(""); return;}
       else salvar.run();
       return;
      }
      if(indice<telefones.size()){
       var telefoneAuxiliar =telefones.get(indice);
       telefone.setId(telefoneAuxiliar.getId());
       telefone.setIdCli(telefoneAuxiliar.getIdCli());
       telefones.set(indice, telefone);
       indice++;
       if(indice<telefones.size()){
           txTelefone.setText( telefones.get(indice).getTelefone());
           if(indice==(telefones.size()-1))botaoSalvar.setText("Salvar");
           return;}
       var respsota =avisoAdicionarMaisUmContato();
       if(respsota) {txTelefone.setText("");return;}
       else salvar.run();
      }
    }
    }
    public void updateTelefones(List<Telefone> l){
    telefones=new ArrayList<>(l);
    if(telefones.size()>0)botaoSalvar.setText("Proximo");
    if(!telefones.isEmpty())updateTelefone(telefones.get(indice));
    }
    public void updateTelefone(Telefone t){
    this.txTelefone.setText(t.getTelefone());
    }
    public String getTelefone(){
    return txTelefone.getText();
    }
    @Override
    public void addNotify(){
        super.addNotify(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        if(telefones.size()>0)botaoSalvar.setText("Prosimo");
    }
    
    
    @Override
    public void finalizar() {
        anterio=null;
        telefones=null;
        salvar=null;
        validar=null;
    }
}
