/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisDeAdicao.paineisAdicaoDeCLientes;

import com.mycompany.meunegocioprojetointegrador.bd.dominio.Endereco;
import com.mycompany.meunegocioprojetointegrador.view.IFinalizar;
import com.mycompany.meunegocioprojetointegrador.view.Temas;
import com.mycompany.meunegocioprojetointegrador.view.respostaParaView.RespostaDeValidacaoDeDados;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author ramon
 */
public class PainelEnderecoCliente extends javax.swing.JPanel implements IFinalizar{
    private InterfaceNavegacaoENtreEstagios anterior,prosimo;
    private List<Endereco> enderecos= new ArrayList<>();
    private int indice=0;
    private Runnable validar;
    /**
     * Creates new form PainelDadosDocliente
     */
    public PainelEnderecoCliente(InterfaceNavegacaoENtreEstagios n,InterfaceNavegacaoENtreEstagios n2,Runnable validar) {
        anterior=n;
        prosimo=n2;
        this.validar=validar;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jLabel2 = new javax.swing.JLabel();
        txRua = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txBairro = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txNumero = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txEstado = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txCidade = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txCep = new javax.swing.JFormattedTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txComplemento = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jbVoultar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jbProximo = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setAlignmentX(CENTER_ALIGNMENT);
        jPanel2.setMaximumSize(new java.awt.Dimension(500, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 100));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel3.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jPanel3.add(filler1);

        jLabel2.setText("Rua");
        jPanel3.add(jLabel2);

        txRua.setAlignmentX(LEFT_ALIGNMENT);
        txRua.setMaximumSize(new java.awt.Dimension(500, 22));
        txRua.setMinimumSize(new java.awt.Dimension(500, 22));
        txRua.setName(""); // NOI18N
        txRua.setPreferredSize(new java.awt.Dimension(500, 22));
        txRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txRuaActionPerformed(evt);
            }
        });
        jPanel3.add(txRua);

        jPanel2.add(jPanel3);

        jPanel10.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel10.setMaximumSize(new java.awt.Dimension(500, 50));
        jPanel10.setMinimumSize(new java.awt.Dimension(500, 50));
        jPanel10.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel10.setRequestFocusEnabled(false);
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        jLabel8.setText("Bairro");
        jPanel10.add(jLabel8);

        txBairro.setAlignmentX(LEFT_ALIGNMENT);
        txBairro.setMaximumSize(new java.awt.Dimension(500, 22));
        txBairro.setMinimumSize(new java.awt.Dimension(500, 22));
        txBairro.setName(""); // NOI18N
        txBairro.setPreferredSize(new java.awt.Dimension(500, 22));
        jPanel10.add(txBairro);

        jPanel2.add(jPanel10);

        jPanel4.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel4.setMaximumSize(new java.awt.Dimension(500, 50));
        jPanel4.setMinimumSize(new java.awt.Dimension(500, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setText("Numero");
        jPanel4.add(jLabel3);

        txNumero.setAlignmentX(LEFT_ALIGNMENT);
        txNumero.setMaximumSize(new java.awt.Dimension(500, 22));
        txNumero.setMinimumSize(new java.awt.Dimension(500, 22));
        txNumero.setName(""); // NOI18N
        txNumero.setPreferredSize(new java.awt.Dimension(500, 22));
        jPanel4.add(txNumero);

        jPanel2.add(jPanel4);

        jPanel5.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel5.setMaximumSize(new java.awt.Dimension(500, 50));
        jPanel5.setMinimumSize(new java.awt.Dimension(500, 50));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setText("Estado");
        jPanel5.add(jLabel4);

        txEstado.setAlignmentX(LEFT_ALIGNMENT);
        txEstado.setMaximumSize(new java.awt.Dimension(500, 22));
        txEstado.setMinimumSize(new java.awt.Dimension(500, 22));
        txEstado.setName(""); // NOI18N
        txEstado.setPreferredSize(new java.awt.Dimension(250, 22));
        jPanel5.add(txEstado);

        jPanel2.add(jPanel5);

        jPanel6.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel6.setMaximumSize(new java.awt.Dimension(500, 50));
        jPanel6.setMinimumSize(new java.awt.Dimension(500, 50));
        jPanel6.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setText("Cidade");
        jPanel6.add(jLabel5);

        txCidade.setAlignmentX(LEFT_ALIGNMENT);
        txCidade.setMaximumSize(new java.awt.Dimension(500, 22));
        txCidade.setMinimumSize(new java.awt.Dimension(500, 22));
        txCidade.setName(""); // NOI18N
        txCidade.setPreferredSize(new java.awt.Dimension(250, 22));
        jPanel6.add(txCidade);

        jPanel2.add(jPanel6);

        jPanel8.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel8.setMaximumSize(new java.awt.Dimension(500, 50));
        jPanel8.setMinimumSize(new java.awt.Dimension(500, 50));
        jPanel8.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel8.setRequestFocusEnabled(false);
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jLabel6.setText("Cep");
        jPanel8.add(jLabel6);

        try {
            txCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txCep.setAlignmentX(0.0F);
        txCep.setMaximumSize(new java.awt.Dimension(500, 22));
        txCep.setMinimumSize(new java.awt.Dimension(500, 22));
        txCep.setPreferredSize(new java.awt.Dimension(500, 22));
        jPanel8.add(txCep);

        jPanel2.add(jPanel8);

        jPanel9.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel9.setMaximumSize(new java.awt.Dimension(500, 50));
        jPanel9.setMinimumSize(new java.awt.Dimension(500, 50));
        jPanel9.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel9.setRequestFocusEnabled(false);
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jLabel7.setText("Complemento");
        jPanel9.add(jLabel7);

        txComplemento.setAlignmentX(LEFT_ALIGNMENT);
        txComplemento.setMaximumSize(new java.awt.Dimension(500, 22));
        txComplemento.setMinimumSize(new java.awt.Dimension(500, 22));
        txComplemento.setName(""); // NOI18N
        txComplemento.setPreferredSize(new java.awt.Dimension(250, 22));
        jPanel9.add(txComplemento);

        jPanel2.add(jPanel9);

        jPanel7.setAlignmentX(
            LEFT_ALIGNMENT);
        jPanel7.setMaximumSize(new java.awt.Dimension(500, 70));
        jPanel7.setMinimumSize(new java.awt.Dimension(500, 70));
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel7.setRequestFocusEnabled(false);
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));

        jbVoultar.setBackground(Temas.backgraundBotoes);
        jbVoultar.setForeground(Temas.foregraundBotoes);
        jbVoultar.setText("voutar");
        jbVoultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoultarActionPerformed(evt);
            }
        });
        jPanel7.add(jbVoultar);
        jPanel7.add(filler2);

        jbProximo.setBackground(Temas.backgraundBotoes);
        jbProximo.setForeground(Temas.foregraundBotoes);
        jbProximo.setText("Proximo");
        jbProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProximoActionPerformed(evt);
            }
        });
        jPanel7.add(jbProximo);

        jPanel2.add(jPanel7);
        jPanel2.add(filler3);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void txRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txRuaActionPerformed

    private void jbVoultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoultarActionPerformed
        if(indice==enderecos.size()){anterior.navegue();return;}
        if(indice>0){
            indice--;
            updateEndereco(enderecos.get(indice));
            return;
        }
        anterior.navegue();
    }//GEN-LAST:event_jbVoultarActionPerformed

    private void jbProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProximoActionPerformed
       validar.run();
    }//GEN-LAST:event_jbProximoActionPerformed
    public void limpartCampos(){
        txBairro.setText("");
        txCep.setText("");
        txCidade.setText("");
        txComplemento.setText("");
        txEstado.setText("");
        txNumero.setText("");
        txRua.setText("");
    }
    public boolean avisoAdicionarMaisUmCliente(){
     var resposta =JOptionPane.showInternalConfirmDialog(jPanel1, 
                                                          "Voce deseja adicionar mais um Endereço ", "Obs:",
                                                          JOptionPane.YES_NO_OPTION,
                                                          JOptionPane.INFORMATION_MESSAGE,
                                                          null);
    if (resposta==JOptionPane.OK_OPTION)return true;
    
    return  false;
    }
    
    public List<Endereco> getLista(){
    return enderecos; 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbProximo;
    private javax.swing.JButton jbVoultar;
    private javax.swing.JTextField txBairro;
    private javax.swing.JFormattedTextField txCep;
    private javax.swing.JTextField txCidade;
    private javax.swing.JTextField txComplemento;
    private javax.swing.JTextField txEstado;
    private javax.swing.JTextField txNumero;
    private javax.swing.JTextField txRua;
    // End of variables declaration//GEN-END:variables

    public void updateEderecos(List<Endereco> l){
    this.enderecos=new ArrayList<>(l);
    if(!l.isEmpty())updateEndereco(enderecos.get(indice));
    }
    public void updateEndereco(Endereco e){
     if(e!=null){
     this.txRua.setText(e.getRua());
     this.txNumero.setText(e.getNumero());
     this.txEstado.setText(e.getEstado());
     this.txCidade.setText(e.getCidade());
     this.txCep.setText(e.getCep());
     this.txBairro.setText(e.getBairo());
     this.txComplemento.setText(e.getComplemento());
     }   

    }
    
    public void notificarValidacao(RespostaDeValidacaoDeDados r){
    if(r instanceof RespostaDeValidacaoDeDados.Invalido i){
    JOptionPane.showMessageDialog(jPanel1,i.mensagem());
    return;
    }
    if(r instanceof RespostaDeValidacaoDeDados.Validado v){
     var endereco=new Endereco(txRua.getText(), 
                                   txCep.getText(),
                                   txCidade.getText(),
                                   txEstado.getText(), 
                                   txNumero.getText(), 
                                   txComplemento.getText(),
                                   null, null,
                                   txBairro.getText());
        
        if(indice==enderecos.size()){
         enderecos.add(endereco);
         indice++;
         if(avisoAdicionarMaisUmCliente()){limpartCampos();return;}
         else prosimo.navegue();
         return;
        }
        if(indice<enderecos.size()){
         var enderecoaux =enderecos.get(indice);
         endereco.setId(enderecoaux.getId());
         endereco.setIdCli(enderecoaux.getIdCli());
         enderecos.set(indice, endereco);
         indice++;
         if(indice<enderecos.size())updateEndereco(enderecos.get(indice));
         else{
          if(avisoAdicionarMaisUmCliente()){limpartCampos();return;}
          else prosimo.navegue();
         }
        }
    }
    }
    
    public String getRua(){
    return txRua.getText();
    }

    public String getBairro() {
        return txBairro.getText();
    }

    public String getCep() {
        var strignvVerificacao =txCep.getText();
        var stringaux=strignvVerificacao.replaceAll("\\D","");
        if(stringaux.isBlank())return "";
        else return strignvVerificacao;
    }

    public String getCidade() {
        return txCidade.getText();
    }

    public String getComplemento() {
        return txComplemento.getText();
    }

    public String getEstado() {
        return txEstado.getText();
    }

    public String getNumero() {
        return txNumero.getText();
    }
    
    @Override
    public void finalizar() {
        anterior=null;
        prosimo=null;
        enderecos=null;
        validar=null;
        
    }
   
  
}
