/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.listas;

import com.mycompany.meunegocioprojetointegrador.bd.dominio.Endereco;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.UIManager;

/**
 *
 * @author ramon
 */
public class PainelEndereco extends javax.swing.JPanel {

    /**
     * Creates new form PainelEndereco
     */
    public PainelEndereco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pRua = new javax.swing.JPanel();
        lIndicativoRua = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        lbRua = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        lbNumero = new javax.swing.JLabel();
        pCep = new javax.swing.JPanel();
        lindicativoCep = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        lbCep = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        lbCidade = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        pRua.setMaximumSize(new java.awt.Dimension(32767, 30));
        pRua.setMinimumSize(new java.awt.Dimension(400, 30));
        pRua.setLayout(new javax.swing.BoxLayout(pRua, javax.swing.BoxLayout.LINE_AXIS));

        lIndicativoRua.setText("Rua :");
        pRua.add(lIndicativoRua);
        pRua.add(filler1);

        lbRua.setText("Rua :");
        lbRua.setMaximumSize(new java.awt.Dimension(250, 16));
        lbRua.setMinimumSize(new java.awt.Dimension(250, 16));
        lbRua.setPreferredSize(new java.awt.Dimension(250, 16));
        pRua.add(lbRua);
        pRua.add(filler2);

        lbNumero.setText("Rua :");
        lbNumero.setMaximumSize(new java.awt.Dimension(50, 16));
        lbNumero.setMinimumSize(new java.awt.Dimension(50, 16));
        lbNumero.setPreferredSize(new java.awt.Dimension(50, 16));
        pRua.add(lbNumero);

        add(pRua);

        pCep.setMaximumSize(new java.awt.Dimension(32767, 30));
        pCep.setMinimumSize(new java.awt.Dimension(400, 30));
        pCep.setLayout(new javax.swing.BoxLayout(pCep, javax.swing.BoxLayout.LINE_AXIS));

        lindicativoCep.setText("Cep:");
        pCep.add(lindicativoCep);
        pCep.add(filler3);

        lbCep.setText("cep");
        lbCep.setMaximumSize(new java.awt.Dimension(100, 16));
        lbCep.setMinimumSize(new java.awt.Dimension(100, 16));
        lbCep.setPreferredSize(new java.awt.Dimension(100, 16));
        pCep.add(lbCep);
        pCep.add(filler4);
        pCep.add(filler5);

        lbCidade.setText("bairo_cidade_Estado");
        lbCidade.setMaximumSize(new java.awt.Dimension(250, 16));
        lbCidade.setMinimumSize(new java.awt.Dimension(250, 16));
        lbCidade.setPreferredSize(new java.awt.Dimension(250, 16));
        pCep.add(lbCidade);

        add(pCep);
    }// </editor-fold>//GEN-END:initComponents
    
    public void updateEndereco(Endereco e){
     lbRua.setText(e.getRua());
     lbNumero.setText(e.getNumero());
     lbCep.setText(e.getCep());
     lbCidade.setText(e.getBairo()+"-"+e.getCidade()+"-"+e.getEstado());
    }
    
    public void selecionadao(boolean selecionado){
        if (selecionado) {
            this.setBackground(Color.darkGray);
            lbRua.setForeground(Color.WHITE);
            lbNumero.setForeground(Color.WHITE);
            lbCep.setForeground(Color.WHITE);
            lbCidade.setForeground(Color.WHITE);
            lIndicativoRua.setForeground(Color.WHITE);
            lindicativoCep.setForeground(Color.WHITE);
            pRua.setBackground(Color.darkGray);
            pCep.setBackground(Color.darkGray);
            return;
        }
       this.setBackground(UIManager.getColor("Painel.background"));
       lbRua.setForeground(Color.BLACK);
       lbNumero.setForeground(Color.BLACK);
       lbCep.setForeground(Color.BLACK);
       lbCidade.setForeground(Color.BLACK);  
       lIndicativoRua.setForeground(Color.BLACK);
       lindicativoCep.setForeground(Color.BLACK);
       pRua.setBackground(UIManager.getColor("Painel.background"));
       pCep.setBackground(UIManager.getColor("Painel.background"));       
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); 
        var grafico2d=(Graphics2D)g.create();
        grafico2d.setColor(Color.WHITE);
        grafico2d.setStroke(new BasicStroke(1f,1,1));
        grafico2d.drawLine(1,this.getHeight()-1,this.getWidth()-1, this.getHeight()-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel lIndicativoRua;
    public javax.swing.JLabel lbCep;
    public javax.swing.JLabel lbCidade;
    public javax.swing.JLabel lbNumero;
    public javax.swing.JLabel lbRua;
    private javax.swing.JLabel lindicativoCep;
    private javax.swing.JPanel pCep;
    private javax.swing.JPanel pRua;
    // End of variables declaration//GEN-END:variables
}
