/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.listas;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.UIManager;

/**
 *
 * @author ramon
 */
public class PainelParaListaDeClientes extends javax.swing.JPanel {
    private boolean seleciondo=false;
    /**
     * Creates new form PainelParaListaDeClientes
     */
    public PainelParaListaDeClientes() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        if(seleciondo){
        var y=this.getHeight();
        var x =this.getWidth();
        var grafic2d=(Graphics2D)g.create();
        grafic2d.setStroke(new BasicStroke(1.5f,1,1));
        grafic2d.setColor(Color.WHITE);
        grafic2d.drawLine(1, y-1, x-1, y-1);
        grafic2d.dispose();
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanelIniciais = new PainelIniciais();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPainelPreviaDados = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        jPanelDocs = new javax.swing.JPanel();
        lTelefone = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        lDoc = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(337, 90));
        setMinimumSize(new java.awt.Dimension(438, 90));
        setPreferredSize(new java.awt.Dimension(337, 90));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(filler1);

        jPanelIniciais.setMaximumSize(new java.awt.Dimension(60, 60));
        jPanelIniciais.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanelIniciais.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanelIniciais.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelIniciaisLayout = new javax.swing.GroupLayout(jPanelIniciais);
        jPanelIniciais.setLayout(jPanelIniciaisLayout);
        jPanelIniciaisLayout.setHorizontalGroup(
            jPanelIniciaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelIniciaisLayout.setVerticalGroup(
            jPanelIniciaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(jPanelIniciais);
        add(filler2);

        jPainelPreviaDados.setMaximumSize(new java.awt.Dimension(32767, 70));
        jPainelPreviaDados.setLayout(new javax.swing.BoxLayout(jPainelPreviaDados, javax.swing.BoxLayout.Y_AXIS));

        lNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lNome.setForeground(new java.awt.Color(0, 0, 0));
        lNome.setText("Nome de teste testavel testando");
        lNome.setAlignmentX(LEFT_ALIGNMENT);
        jPainelPreviaDados.add(lNome);

        jPanelDocs.setAlignmentX(LEFT_ALIGNMENT);
        jPanelDocs.setAlignmentY(LEFT_ALIGNMENT);
        jPanelDocs.setMaximumSize(new java.awt.Dimension(12000, 30));
        jPanelDocs.setLayout(new javax.swing.BoxLayout(jPanelDocs, javax.swing.BoxLayout.LINE_AXIS));

        lTelefone.setForeground(new java.awt.Color(0, 0, 0));
        lTelefone.setText("Tel : xx xxxxx xxxx");
        jPanelDocs.add(lTelefone);
        jPanelDocs.add(filler4);

        lDoc.setForeground(new java.awt.Color(0, 0, 0));
        lDoc.setText("Doc : xxx.xxx.xxx-xx");
        jPanelDocs.add(lDoc);

        jPainelPreviaDados.add(jPanelDocs);

        add(jPainelPreviaDados);
    }// </editor-fold>//GEN-END:initComponents

    public void setIniciais(String s){
    var paine=(PainelIniciais)jPanelIniciais;
    paine.setInicial(s);
    paine.repaint();
    }
    public void selecionado(boolean selecao){
        seleciondo=selecao;
     if(selecao){   
    this.setBackground(Color.DARK_GRAY);
    jPainelPreviaDados.setBackground(Color.DARK_GRAY);
    jPanelDocs.setBackground(Color.DARK_GRAY);
    jPanelIniciais.setBackground(Color.DARK_GRAY);
    lNome.setForeground(Color.WHITE);
    lTelefone.setForeground(Color.WHITE);
    lDoc.setForeground(Color.WHITE);
     }
     else{
     Color foreground = UIManager.getColor("Panel.background");
    this.setBackground(foreground);
    jPainelPreviaDados.setBackground(foreground);
    jPanelDocs.setBackground(foreground);
    jPanelIniciais.setBackground(foreground);
    lNome.setForeground(Color.BLACK);
    lTelefone.setForeground(Color.BLACK);
    lDoc.setForeground(Color.BLACK);
     }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel jPainelPreviaDados;
    private javax.swing.JPanel jPanelDocs;
    private javax.swing.JPanel jPanelIniciais;
    public javax.swing.JLabel lDoc;
    public javax.swing.JLabel lNome;
    public javax.swing.JLabel lTelefone;
    // End of variables declaration//GEN-END:variables
}
