/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.listas;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.UIManager;

/**
 *
 * @author ramon
 */
public class PainelTelefone extends javax.swing.JPanel {

    /**
     * Creates new form PainelTelefone
     */
    public PainelTelefone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTelefone = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        lTelefone.setText("jLabel1");
        lTelefone.setMaximumSize(new java.awt.Dimension(20202, 16));
        add(lTelefone);
    }// </editor-fold>//GEN-END:initComponents

    public void selecionado(boolean  selecionado){
     if(selecionado){
      this.setBackground(Color.DARK_GRAY);
      lTelefone.setForeground(Color.WHITE);
      return;
     }
     this.setBackground(UIManager.getColor("Panel.background"));
     this.lTelefone.setForeground(Color.BLACK);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        var grafico2d=(Graphics2D)g.create();
        grafico2d.setColor(Color.WHITE);
        grafico2d.setStroke(new BasicStroke(0.5f,1,1));
        grafico2d.drawLine(0,this.getHeight()-1,this.getWidth()-1,this.getHeight()-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lTelefone;
    // End of variables declaration//GEN-END:variables
}
