/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.listas;

import com.mycompany.meunegocioprojetointegrador.view.Temas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author ramon
 */
public class PainelIniciais extends javax.swing.JPanel {
    private String iniciais;
    private Color[] cores = new Color[]{};
    /**
     * Creates new form PainelIniciais
     */
    public PainelIniciais() {
        initComponents();
        this.setPreferredSize(new Dimension(60,60));
        iniciais="N";
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); 
        var minimo=Integer.min(this.getHeight(),this.getWidth())-10;
        var grafics2d=(Graphics2D)g.create();
        grafics2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        var cor =Temas.getCorPorInicias(iniciais.toCharArray()[0]);
        var posicaox=(this.getWidth()-minimo)/2;
        var posicaoy=(this.getHeight()-minimo)/2;
        var font = new Font(Font.SERIF,Font.BOLD, 30);
        grafics2d.setFont(font);
        var fontmetrics =grafics2d.getFontMetrics();
        var larguraTexto=fontmetrics.stringWidth(iniciais);
        var autura =fontmetrics.getHeight();
        var x = (this.getWidth()-larguraTexto)/2;
        var y =((this.getHeight()-autura)/2)+fontmetrics.getAscent();
        grafics2d.setColor(cor);
        grafics2d.fillOval(posicaox,posicaoy,minimo,minimo);
        grafics2d.setColor(Temas.foregraundBotoes);
        grafics2d.drawString(iniciais,x,y);
        grafics2d.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(50, 50));
        setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
      
    public void setInicial(String s){
    iniciais=s.toUpperCase();}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
