/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.listas;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.plaf.basic.BasicBorders;

/**
 *
 * @author ramon
 */
public class PainelCelulasHEader extends javax.swing.JPanel {

    /**
     * Creates new form PainelCelulasHEader
     */
    public PainelCelulasHEader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lDado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lDado.setForeground(new java.awt.Color(0, 0, 0));
        lDado.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lDado, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lDado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
     
    public void setWith(int largura){
    this.setMaximumSize(new Dimension(largura,this.getHeight()));
    }

    @Override
    protected void paintComponent(Graphics g) {
       super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
       var grafico2d=(Graphics2D)g.create();
       grafico2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
       var y =this.getHeight();
       var x =this.getWidth();
       grafico2d.setColor(Color.LIGHT_GRAY);
       grafico2d.setStroke(new BasicStroke(4f,1,1));
       grafico2d.drawLine(0,y,x, y);
       grafico2d.setStroke(new BasicStroke(0.5f,1,1));
       grafico2d.drawLine(x-1, 0, x-1, y);
       grafico2d.dispose();
    
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lDado;
    // End of variables declaration//GEN-END:variables
}
