/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisPrincipais.painelRequisicoes;

import com.mycompany.meunegocioprojetointegrador.bd.dominio.DadosDaRequisicao;
import com.mycompany.meunegocioprojetointegrador.view.Temas;
import com.mycompany.meunegocioprojetointegrador.view.controles.ControleRequisicoes;
import com.mycompany.meunegocioprojetointegrador.view.controles.validador.EnumPesquisaRequisicao;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.GerenciadorDepaineis.INavegar;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.ModeloTabelaDeRequisicoes;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.GerenciadorDepaineis.Painel;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.Rotas;
import com.mycompany.meunegocioprojetointegrador.view.paineis.Util.PainelLoadBarraCircular;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.ModeloOPcaoPesquisaRequisicao;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.RenderCelTabelaPRoduto;
import com.mycompany.meunegocioprojetointegrador.view.respostaParaView.RespostaDeLoad;
import java.awt.Color;
import java.util.List;
import javax.management.InstanceNotFoundException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ramon
 */
public class PainelRequisicoes extends Painel {
    private INavegar navegar ;
    private ControleRequisicoes controle;
    /**
     * Creates new form PainelRequisicoes
     */
    public PainelRequisicoes(ControleRequisicoes c,INavegar navegarParaEditarAdicionar) {
        controle=c;
        this.navegar=navegarParaEditarAdicionar;
        initComponents();
        jComboBox1.setSelectedIndex(1);
        controle.getEstadoDaLista().observar((l)->{
         ((ModeloTabelaDeRequisicoes)jTable1.getModel()).updadteLista((List<DadosDaRequisicao>) l);
        },this);
        controle.getEstadoLoadListas().observar((load)->{
        if(load instanceof  RespostaDeLoad.Load){
        jPAnimacaoLoadPesquisa.setVisible(true);
        }
        if(load instanceof RespostaDeLoad.Erro er){
        JOptionPane.showMessageDialog(jPanel1,er.mensagem());
        jPAnimacaoLoadPesquisa.setVisible(false);
        }
        if(load instanceof RespostaDeLoad.OK){
        jPAnimacaoLoadPesquisa.setVisible(false);
        }
        if(load instanceof RespostaDeLoad.OKVasio){
        jPAnimacaoLoadPesquisa.setVisible(false);
        }
        },this);
        controle.getEstadoLoadExclusao().observar((r)->{
        if(r instanceof  RespostaDeLoad.Load){
        jPAnimcaoLoadEsclusao.setVisible(true);
        }
        if(r instanceof RespostaDeLoad.Erro er){
        JOptionPane.showMessageDialog(jPanel1,er.mensagem());
        jPAnimcaoLoadEsclusao.setVisible(false);
        }
        if(r instanceof RespostaDeLoad.OK){
        jPAnimcaoLoadEsclusao.setVisible(false);
        }
        if(r instanceof RespostaDeLoad.OKVasio){
        jPAnimcaoLoadEsclusao.setVisible(false);
        }
        
        },this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jComboBox1 = new javax.swing.JComboBox<>();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton1 = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPAnimacaoLoadPesquisa = new PainelLoadBarraCircular();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton3 = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton4 = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton5 = new javax.swing.JButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPAnimcaoLoadEsclusao = new PainelLoadBarraCircular();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(32767, 5), new java.awt.Dimension(32767, 5), new java.awt.Dimension(32767, 5));
        jLabel1 = new JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));

        setAlignmentX(CENTER_ALIGNMENT);
        setAlignmentY(CENTER_ALIGNMENT);
        setMaximumSize(new java.awt.Dimension(32767, 900));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setRequestFocusEnabled(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setAlignmentX(CENTER_ALIGNMENT);
        jPanel1.setAlignmentY(CENTER_ALIGNMENT);
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(filler2);

        jPanel2.setAlignmentX(LEFT_ALIGNMENT);
        jPanel2.setMaximumSize(new java.awt.Dimension(600, 60));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 60));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTextField1.setMaximumSize(new java.awt.Dimension(200, 22));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jPanel2.add(filler3);

        jComboBox1.setModel(new ModeloOPcaoPesquisaRequisicao());
        jComboBox1.setMaximumSize(new java.awt.Dimension(100, 22));
        jPanel2.add(jComboBox1);
        jPanel2.add(filler4);

        jButton1.setBackground(Temas.backgraundBotoes);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(23, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(23, 23));
        jButton1.setOpaque(true);
        jButton1.setPreferredSize(new java.awt.Dimension(23, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jPanel2.add(filler9);

        jPAnimacaoLoadPesquisa.setMaximumSize(new java.awt.Dimension(23, 23));
        jPAnimacaoLoadPesquisa.setMinimumSize(new java.awt.Dimension(23, 23));
        jPAnimacaoLoadPesquisa.setPreferredSize(new java.awt.Dimension(23, 23));
        jPAnimacaoLoadPesquisa.setRequestFocusEnabled(false);
        jPanel2.add(jPAnimacaoLoadPesquisa);

        jPanel1.add(jPanel2);

        jPanel3.setAlignmentX(LEFT_ALIGNMENT);
        jPanel3.setMaximumSize(new java.awt.Dimension(500, 60));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jButton2.setText("Excluir");
        jButton2.setMaximumSize(new java.awt.Dimension(102, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(102, 30));
        jButton2.setBackground(Temas.backgraundBotoes);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jPanel3.add(filler5);

        jButton3.setBackground(Temas.backgraundBotoes);
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jButton3.setText("Editar");
        jButton3.setMaximumSize(new java.awt.Dimension(102, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(102, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jPanel3.add(filler6);

        jButton4.setBackground(Temas.backgraundBotoes);
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jButton4.setText("Adicionar");
        jButton4.setMaximumSize(new java.awt.Dimension(102, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(102, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jPanel3.add(filler7);

        jButton5.setBackground(Temas.backgraundBotoes);
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visibility_18dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jButton5.setText("Visualizar");
        jButton5.setMaximumSize(new java.awt.Dimension(110, 30));
        jButton5.setMinimumSize(new java.awt.Dimension(110, 30));
        jButton5.setPreferredSize(new java.awt.Dimension(110, 30));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jPanel3.add(filler10);

        jPAnimcaoLoadEsclusao.setMaximumSize(new java.awt.Dimension(30, 30));
        jPAnimcaoLoadEsclusao.setMinimumSize(new java.awt.Dimension(30, 30));
        jPAnimcaoLoadEsclusao.setPreferredSize(new java.awt.Dimension(30, 30));
        jPAnimcaoLoadEsclusao.setLayout(new javax.swing.BoxLayout(jPAnimcaoLoadEsclusao, javax.swing.BoxLayout.Y_AXIS));
        jPAnimcaoLoadEsclusao.add(filler11);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_23dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(20, 20));
        jPAnimcaoLoadEsclusao.add(jLabel1);

        jPanel3.add(jPAnimcaoLoadEsclusao);

        jPanel1.add(jPanel3);
        jPanel1.add(filler8);

        jScrollPane1.setAlignmentX(LEFT_ALIGNMENT);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(700, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 400));

        jTable1.setModel(new ModeloTabelaDeRequisicoes());
        var modeloDeCOluna=jTable1.getColumnModel();
        modeloDeCOluna.getColumn(0).setPreferredWidth(100);
        modeloDeCOluna.getColumn(1).setPreferredWidth(500);
        modeloDeCOluna.getColumn(2).setPreferredWidth(100);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        var tableHeader=jTable1.getTableHeader();
        tableHeader.setDefaultRenderer(new RenderCelTabelaPRoduto());
        jTable1.setSelectionBackground(Color.DARK_GRAY);
        jTable1.setSelectionForeground(Color.WHITE);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);

        add(jPanel1);
        add(filler1);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        var item = jTable1.getSelectedRows();
        if(item.length>1){
        JOptionPane.showMessageDialog(jPanel1,"E nessesario selecionar apenas uma requisicao por vez para excluir");
        return;
        }
        if(item.length<=0){
        JOptionPane.showMessageDialog(jPanel1,"Nenhuma requisicoa foi selecionada");
        return;
        }
        var resposta =JOptionPane.showConfirmDialog(jPanel1,"Ao excluir todos os dados referentes a essa requisicao serao perdidos", "Obs",JOptionPane.YES_NO_OPTION);
        if(resposta==JOptionPane.NO_OPTION)return;
        
        controle.Escluir(((ModeloTabelaDeRequisicoes)jTable1.getModel()).getItemSelecionado(item[0]));
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        navegar.navegar(new Rotas.AdicionarRequisicao(null));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      var itensSelecionados =jTable1.getSelectedRows();
      if(itensSelecionados.length>1){avisoItemsDemaisSelecionados("Visualizacao");return;}
      if(itensSelecionados.length<1){avisoNenhunItemSelecionado("Visualizacao");return;}
      var item=((ModeloTabelaDeRequisicoes)jTable1.getModel()).getItemSelecionado(itensSelecionados[0]);
      navegar.navegar(new Rotas.VisualizarRequisicao(item));
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      var itensSelecionados =jTable1.getSelectedRows();
      if(itensSelecionados.length>1){avisoItemsDemaisSelecionados("Edicao");return;}
      if(itensSelecionados.length<1){avisoNenhunItemSelecionado("Edicao");return;}
      var item=((ModeloTabelaDeRequisicoes)jTable1.getModel()).getItemSelecionado(itensSelecionados[0]);
      navegar.navegar(new Rotas.AdicionarRequisicao(item));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controle.pesquisar((EnumPesquisaRequisicao)jComboBox1.getSelectedItem(),jTextField1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void avisoItemsDemaisSelecionados(String acao){
        JOptionPane.showMessageDialog(this,"E nessesario selecionar apenas um item para a "+acao,"Atenção",JOptionPane.INFORMATION_MESSAGE);
       
    }
    
    private void avisoNenhunItemSelecionado(String acao){
     JOptionPane.showMessageDialog(this,"Nenhum item foi selecionadao para "+acao,"Atenção",JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<EnumPesquisaRequisicao> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPAnimacaoLoadPesquisa;
    private javax.swing.JPanel jPAnimcaoLoadEsclusao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciar() {
        super.iniciar(); 
        controle.caregarListaInical();
    
    }

    @Override
    public void finalizar() {
        super.finalizar(); 
      this.controle.finalizar();
      this.controle=null;
      this.navegar=null;
    }


}
