/*
 * Click nbfs://nbhost/SystemFi            @Override
            public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public Insets getBorderInsets(Component c) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public boolean isBorderOpaque() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        }eSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.navegacao;

import com.mycompany.meunegocioprojetointegrador.view.Temas;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.Stroke;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author ramon
 */
public class BaraLateral extends javax.swing.JPanel {
    private IAcaodenavegar acoes;
    private int inicio=0;
    private int tamanhoIcone=45;
    private int desenhoAnimado=0;
    private Timer timerAnimacao;
    private Animacao estado;
    private Timer animacaoAparecer;
    private Timer animacaoDesaparecer;
    /**
     * Creates new form BaraLateral
     */
    public BaraLateral(IAcaodenavegar navegar) {
        initComponents();
        acoes=navegar;
        inicio=iconeRequisicoes.getY();
        tamanhoIcone=iconeRequisicoes.getHeight();
        repaint();
        
    }
 
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        iconeClientes = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        iconeRequisicoes = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        iconeProdutos = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(60, 700));
        setPreferredSize(new java.awt.Dimension(60, 32767));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(filler3);

        iconeClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/person.png"))); // NOI18N
        iconeClientes.setAlignmentX(0.5F);
        iconeClientes.setBorder(new javax.swing.border.MatteBorder(null));
        iconeClientes.setMinimumSize(new java.awt.Dimension(90, 90));
        iconeClientes.setName(""); // NOI18N
        iconeClientes.setPreferredSize(new java.awt.Dimension(90, 90));
        iconeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconeClientesMouseClicked(evt);
            }
        });
        add(iconeClientes);
        add(filler1);

        iconeRequisicoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory_34dp_000000_FILL0_wght400_GRAD0_opsz40.png"))); // NOI18N
        iconeRequisicoes.setAlignmentX(0.5F);
        iconeRequisicoes.setBorder(new javax.swing.border.MatteBorder(null));
        iconeRequisicoes.setMaximumSize(new java.awt.Dimension(35, 35));
        iconeRequisicoes.setMinimumSize(new java.awt.Dimension(35, 35));
        iconeRequisicoes.setName(""); // NOI18N
        iconeRequisicoes.setPreferredSize(new java.awt.Dimension(35, 35));
        iconeRequisicoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconeRequisicoesMouseClicked(evt);
            }
        });
        add(iconeRequisicoes);
        add(filler2);

        iconeProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingmode_34dp_000000_FILL0_wght400_GRAD0_opsz40.png"))); // NOI18N
        iconeProdutos.setAlignmentX(0.5F);
        iconeProdutos.setBorder(new javax.swing.border.MatteBorder(null));
        iconeProdutos.setMaximumSize(new java.awt.Dimension(35, 35));
        iconeProdutos.setMinimumSize(new java.awt.Dimension(35, 35));
        iconeProdutos.setName(""); // NOI18N
        iconeProdutos.setPreferredSize(new java.awt.Dimension(90, 90));
        iconeProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconeProdutosMouseClicked(evt);
            }
        });
        add(iconeProdutos);
    }// </editor-fold>//GEN-END:initComponents

    private void iconeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconeClientesMouseClicked
        setScroll(iconeClientes);
        
        acoes.navegar(new Rotas.Clientes());
       
    }//GEN-LAST:event_iconeClientesMouseClicked

    private void iconeRequisicoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconeRequisicoesMouseClicked
        setScroll(iconeRequisicoes);
        acoes.navegar(new Rotas.Requisicoes());
        
    }//GEN-LAST:event_iconeRequisicoesMouseClicked

    private void iconeProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconeProdutosMouseClicked
        setScroll(iconeProdutos);
        acoes.navegar(new Rotas.Produtos());
        
    }//GEN-LAST:event_iconeProdutosMouseClicked

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); 
        var grafics2d =(Graphics2D)g.create();
        grafics2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
        grafics2d.setColor(Color.LIGHT_GRAY);
        grafics2d.setStroke(new BasicStroke(0.5f,1,1));
        grafics2d.drawLine(this.getWidth(),0,this.getWidth(),this.getHeight());
        grafics2d.setColor(Temas.backgraundBotoes);
        grafics2d.fillRoundRect(3,desenhoAnimado,3,35,10,10);
        
        grafics2d.dispose();
    }
     
    private void setScroll(Component c){
        
        desenhoAnimado=inicio;
        inicio=c.getY();
        tamanhoIcone=c.getHeight();
        if(desenhoAnimado>inicio){
            estado=Animacao.Subindo;
           timerAnimacao.start();
        }
        if(desenhoAnimado<inicio){
            estado=Animacao.Decendo;
            timerAnimacao.start();
        }
        
    }
    
    
    @Override
    public void removeNotify() {
        super.removeNotify();
        if(timerAnimacao!=null&&timerAnimacao.isRunning())timerAnimacao.stop();
        if(animacaoAparecer!=null&&animacaoAparecer.isRunning())animacaoAparecer.stop();
        if(animacaoDesaparecer!=null&&animacaoDesaparecer.isRunning())animacaoDesaparecer.stop();
        animacaoAparecer=null;
        animacaoDesaparecer=null;
        timerAnimacao= null;
    }

    @Override
    public void addNotify() {
        super.addNotify(); 
        timerAnimacao = new Timer(16, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                switch (estado) {
                    case Decendo->{
                    desenhoAnimado+=5;
                    if(desenhoAnimado>inicio)desenhoAnimado=inicio;
                    if(desenhoAnimado==inicio)timerAnimacao.stop();
                    }
                    case Subindo->{
                                        
                    desenhoAnimado-=5;
                    if(desenhoAnimado<inicio)desenhoAnimado=inicio;
                    if(desenhoAnimado==inicio)timerAnimacao.stop();
                    
                    }
                 }
                repaint();
            }
        });
        
        animacaoAparecer=new Timer(16,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            
            var largura =getWidth();
            if(animacaoDesaparecer.isRunning())animacaoDesaparecer.stop();
            if(largura>=60){
             animacaoAparecer.stop();
                setPreferredSize(new Dimension(60,getHeight()));
                doLayout();
                revalidate();
                repaint();
             return;
            }
                setPreferredSize(new Dimension(largura+5,getHeight()));
                doLayout();
                revalidate();
                repaint();
            }
        });
        
        animacaoDesaparecer= new Timer(16,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            var largura=getWidth();
            if(animacaoAparecer.isRunning())animacaoAparecer.stop();
            if(largura<=0){
                animacaoDesaparecer.stop();
                setVisible(false);
                doLayout();
                revalidate();
                repaint();
                return;
            }
                setPreferredSize(new Dimension(largura-10,getHeight()));
                doLayout();
                revalidate();
                repaint();
            }
        });
    }
    
    public void apartecer(){
    if(isVisible())return;
    setVisible(true);
    animacaoAparecer.start();
    }
    public void desaparecer(){
     if(!isVisible())return;
    animacaoDesaparecer.start();
    }
    public void setIconeSelecionado(int indice){
        switch (indice) {
            case 0->{setScroll(iconeClientes);}
            case 1->{setScroll(iconeRequisicoes);}
            case 2->{setScroll(iconeProdutos);}
            default ->{throw new IllegalArgumentException("incice selecionada noa representa nenhum dos icones na barra");}
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel iconeClientes;
    private javax.swing.JLabel iconeProdutos;
    private javax.swing.JLabel iconeRequisicoes;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

private enum Animacao{
 Subindo,Decendo;
}
}
