/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisDeAdicao.painelAdicaoRequisicao;

import com.mycompany.meunegocioprojetointegrador.view.IFinalizar;
import com.mycompany.meunegocioprojetointegrador.view.Temas;
import com.mycompany.meunegocioprojetointegrador.view.controles.validador.Par;
import com.mycompany.meunegocioprojetointegrador.view.paineis.Util.PainelLoadBarraCircular;
import com.mycompany.meunegocioprojetointegrador.view.paineis.Util.util.PainelComBorda;
import javax.swing.JOptionPane;

/**
 *
 * @author ramon
 */
public class PainelDeObservacoes extends javax.swing.JPanel implements IFinalizar{
    private Runnable anterior;
    private Runnable salvar;
    private Runnable update;
    /**
     * Creates new form PainelDeSelecao
     */
    public PainelDeObservacoes(Runnable anterior,Runnable salvar,Runnable update) {
        this.anterior=anterior;
        this.salvar=salvar;
        this.update=update;
        initComponents();
        jPAnimacao.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jLabel1 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescricao = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jLabel2 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAObservacao = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPAnimacao = new PainelLoadBarraCircular() ;
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton2 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setMaximumSize(new java.awt.Dimension(313131, 900));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setAlignmentX(0.5F);
        jPanel2.setMaximumSize(new java.awt.Dimension(400, 150));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 150));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        jPanel2.add(filler2);

        jLabel1.setText("Descricao");
        jPanel2.add(jLabel1);
        jPanel2.add(filler5);

        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 90));

        jTADescricao.setColumns(20);
        jTADescricao.setRows(5);
        jScrollPane1.setViewportView(jTADescricao);

        jPanel2.add(jScrollPane1);

        jPanel1.add(jPanel2);

        jPanel3.setAlignmentX(0.5F);
        jPanel3.setMaximumSize(new java.awt.Dimension(400, 150));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 150));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jPanel3.add(filler1);

        jLabel2.setText("Observacao");
        jPanel3.add(jLabel2);
        jPanel3.add(filler4);

        jScrollPane2.setAlignmentX(0.0F);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(32767, 90));

        jTAObservacao.setColumns(20);
        jTAObservacao.setRows(5);
        jScrollPane2.setViewportView(jTAObservacao);

        jPanel3.add(jScrollPane2);

        jPanel1.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(600, 100));
        jPanel4.setMinimumSize(new java.awt.Dimension(600, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(600, 100));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("Voutar");
        jButton1.setBackground(Temas.backgraundBotoes);
        jButton1.setForeground(Temas.foregraundBotoes);
        jButton1.setMaximumSize(new java.awt.Dimension(120, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(120, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(120, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jPanel4.add(filler6);

        jPAnimacao.setMaximumSize(new java.awt.Dimension(50, 50));
        jPAnimacao.setMinimumSize(new java.awt.Dimension(50, 50));
        jPAnimacao.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel4.add(jPAnimacao);
        jPanel4.add(filler7);

        jButton2.setText("Salvar");
        jButton2.setBackground(Temas.backgraundBotoes);
        jButton2.setForeground(Temas.foregraundBotoes);
        jButton2.setMaximumSize(new java.awt.Dimension(120, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(120, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(120, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jPanel1.add(jPanel4);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        anterior.run();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jTADescricao.getText().isBlank()){
            JOptionPane.showMessageDialog(jPanel1,"A descricao da requisicao esta vasia");
            return;
        }
        update.run();
        salvar.run();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void avisoErro(String mensagem){
    JOptionPane.showMessageDialog(jPanel1, mensagem);
    }
    
    public void iniciarAnimacao(){
        var animacao=(PainelLoadBarraCircular)this.jPAnimacao;
        animacao.setVisible(true);
    }
    public void pararAnimacao(){
        var animacao=(PainelLoadBarraCircular)this.jPAnimacao;
        animacao.setVisible(false);
    }
    
    public Par<String,String> getDados(){
    return new Par<>(jTADescricao.getText(),jTAObservacao.getText());
    }
    
    public void setarDados(Par<String,String> p){
    if(p!=null) {   
    jTADescricao.setText(p.primeiro());
    jTAObservacao.setText(p.segundo());}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPAnimacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTADescricao;
    private javax.swing.JTextArea jTAObservacao;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void finalizar() {
    salvar=null;
    anterior=null;
    
    }
}
