/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisDeAdicao.painelAdicaoRequisicao;
import com.mycompany.meunegocioprojetointegrador.bd.dominio.ProdutoSelecionado;
import com.mycompany.meunegocioprojetointegrador.bd.dominio.ProdutoServico;
import com.mycompany.meunegocioprojetointegrador.view.IFinalizar;
import com.mycompany.meunegocioprojetointegrador.view.Temas;
import com.mycompany.meunegocioprojetointegrador.view.controles.validador.EnumPesquisaProdutos;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.ModeloComboBoxPesquisaProdutos;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.ModeloProdutoSelecionado;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.ModeloTabelaProdutos;
import com.mycompany.meunegocioprojetointegrador.view.paineis.Util.util.FillerLinhaSeparadora;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author ramon
 */
public class PainelSelecaoDeprodutos extends javax.swing.JPanel implements IFinalizar{
    private Runnable anterior;
    private Runnable proximo;
    private Runnable adicionarObjeto;
    private Runnable encrementarProduto;
    private Runnable decrementarProduto;
    private Runnable pesquisar;
    /**
     * Creates new form PainelSelecaoDeprodutos
     */
    public PainelSelecaoDeprodutos(Runnable anterior,
                                   Runnable proximo,
                                   Runnable adicionarObjetoRunnable,
                                   Runnable encrementarProdutoRunnable,
                                   Runnable decrementarRunnable,
                                   Runnable pesquisar) {
        this.encrementarProduto=encrementarProdutoRunnable;
        this.decrementarProduto=decrementarRunnable;
        this.anterior=anterior;
        this.proximo=proximo;
        this.adicionarObjeto=adicionarObjetoRunnable;
        this.pesquisar=pesquisar;
        initComponents();
        jComboBox1.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel4 = new javax.swing.JPanel();
        jTPesquisa = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jComboBox1 = new javax.swing.JComboBox<>();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProdutos = new javax.swing.JTable();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jButton3 = new javax.swing.JButton();
        filler1 = new FillerLinhaSeparadora(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 32767));
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100));
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProdutosSelecionados = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton6 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 900));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(395, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(395, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(395, 600));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Selecao de  Produtos");
        jPanel2.add(jLabel1);
        jPanel2.add(filler2);

        jPanel4.setAlignmentX(0.0F);
        jPanel4.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel4.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel4.setVerifyInputWhenFocusTarget(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jTPesquisa.setMaximumSize(new java.awt.Dimension(200, 22));
        jTPesquisa.setMinimumSize(new java.awt.Dimension(200, 22));
        jPanel4.add(jTPesquisa);
        jPanel4.add(filler3);

        jComboBox1.setModel(new ModeloComboBoxPesquisaProdutos());
        jComboBox1.setMaximumSize(new java.awt.Dimension(100, 22));
        jComboBox1.setMinimumSize(new java.awt.Dimension(100, 22));
        jComboBox1.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel4.add(jComboBox1);
        jPanel4.add(filler4);

        jButton1.setBackground(Temas.backgraundBotoes);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(23, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(23, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(23, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jPanel2.add(jPanel4);

        jButton2.setBackground(Temas.backgraundBotoes);
        jButton2.setForeground(Temas.foregraundBotoes);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jButton2.setText("Adicionar A produtos Selecionados");
        jButton2.setMaximumSize(new java.awt.Dimension(252, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(102, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jPanel2.add(filler6);

        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(400, 200));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 200));

        jTProdutos.setForeground(java.awt.Color.black);
        jTProdutos.setModel(new ModeloTabelaProdutos());
        var modeloDaColuna=jTProdutos.getColumnModel();
        modeloDaColuna.getColumn(0).setMaxWidth(30);
        modeloDaColuna.getColumn(3).setMaxWidth(50);
        jTProdutos.setAlignmentX(0.0F);
        jTProdutos.setSelectionBackground(java.awt.Color.darkGray);
        jTProdutos.setSelectionForeground(java.awt.Color.white);
        jScrollPane1.setViewportView(jTProdutos);

        jPanel2.add(jScrollPane1);
        jPanel2.add(filler7);

        jButton3.setText("Voutar");
        jButton3.setBackground(Temas.backgraundBotoes);
        jButton3.setForeground(Temas.foregraundBotoes);
        jButton3.setMaximumSize(new java.awt.Dimension(102, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(102, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jPanel1.add(jPanel2);

        filler1.setMaximumSize(new java.awt.Dimension(10, 600));
        filler1.setMinimumSize(new java.awt.Dimension(10, 600));
        filler1.setPreferredSize(new java.awt.Dimension(10, 600));
        jPanel1.add(filler1);

        jPanel3.setMaximumSize(new java.awt.Dimension(395, 600));
        jPanel3.setMinimumSize(new java.awt.Dimension(395, 600));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Produtos Selecionados");
        jPanel3.add(jLabel2);
        jPanel3.add(filler5);

        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAutoscrolls(true);
        jPanel5.setMaximumSize(new java.awt.Dimension(300, 50));
        jPanel5.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exposure_plus_1_23dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton4.setText("Adicionar");
        jButton4.setBackground(Temas.backgraundBotoes);
        jButton4.setForeground(Temas.foregraundBotoes);
        jButton4.setMaximumSize(new java.awt.Dimension(122, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(122, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(122, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jPanel5.add(filler8);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exposure_neg_1_23dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton5.setText("Remover");
        jButton5.setBackground(Temas.backgraundBotoes);
        jButton5.setForeground(Temas.foregraundBotoes);
        jButton5.setMaximumSize(new java.awt.Dimension(122, 30));
        jButton5.setMinimumSize(new java.awt.Dimension(122, 30));
        jButton5.setPreferredSize(new java.awt.Dimension(122, 30));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);

        jPanel3.add(jPanel5);

        jScrollPane2.setAlignmentX(0.0F);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(400, 200));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(400, 200));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(400, 200));

        jTProdutosSelecionados.setModel(new ModeloProdutoSelecionado());
        var columModel=jTProdutosSelecionados.getColumnModel();
        //columModel.getColumn(0).setMaxWidth(100);
        columModel.getColumn(1).setMaxWidth(80);
        columModel.getColumn(2).setMaxWidth(50);
        columModel.getColumn(3).setMaxWidth(70);
        jTProdutosSelecionados.setAlignmentX(0.0F);
        jTProdutosSelecionados.setSelectionBackground(java.awt.Color.darkGray);
        jTProdutosSelecionados.setSelectionForeground(java.awt.Color.white);
        jScrollPane2.setViewportView(jTProdutosSelecionados);

        jPanel3.add(jScrollPane2);

        jPanel6.setAlignmentX(0.0F);
        jPanel6.setMaximumSize(new java.awt.Dimension(400, 70));
        jPanel6.setMinimumSize(new java.awt.Dimension(400, 70));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));
        jPanel6.add(filler9);

        jButton6.setText("Proximo");
        jButton6.setBackground(Temas.backgraundBotoes);
        jButton6.setForeground(Temas.foregraundBotoes);
        jButton6.setMaximumSize(new java.awt.Dimension(102, 30));
        jButton6.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton6.setPreferredSize(new java.awt.Dimension(102, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6);

        jPanel3.add(jPanel6);

        jPanel1.add(jPanel3);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       if(((ModeloProdutoSelecionado)jTProdutosSelecionados.getModel()).listavasia()){
       JOptionPane.showMessageDialog(jPanel1,"Nenhum produto foi selecionado");
       return;
       }
        proximo.run();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        anterior.run();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        var indices=jTProdutos.getSelectedRows();
        if(indices.length>1){
            JOptionPane.showMessageDialog(jPanel1,"E presisso selecionar apenas um produto para adicionar a lista");
            return;
        }
        if(indices.length<=0){
        JOptionPane.showMessageDialog(jPanel1,"Nenhum item foi selecionadao para ser adicionadoa");
        return;
        }
        this.adicionarObjeto.run();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if(!checarSelecaoPRodutos())return;
       encrementarProduto.run();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(!checarSelecaoPRodutos())return;
        decrementarProduto.run();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pesquisar.run();
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean  checarSelecaoPRodutos(){
    var items =jTProdutosSelecionados.getSelectedRows();
    if(items.length>1){
    JOptionPane.showMessageDialog(jPanel1,"E presiso selecionar apenas um item para operecao");
    return false;
    }
    if(items.length<=0){
    JOptionPane.showMessageDialog(jPanel1,"Nenhum item selecionado para operacao");
    return false;
    }
    return true;
    }
    
    
    public ProdutoSelecionado getProdutoSelecionado(){
    var produtoEscolhido= ((ModeloTabelaProdutos)jTProdutos.getModel()).getSelecao(jTProdutos.getSelectedRow());
    var produto = new ProdutoSelecionado(null, null, produtoEscolhido.getId(),produtoEscolhido.getNome(),produtoEscolhido.isServico(),1l, produtoEscolhido.getPreco());
    return produto;
            }
    
    public int indiceProdutoSelecionado(){
    return jTProdutosSelecionados.getSelectedRow();
    }
    
    public EnumPesquisaProdutos getTipoPesquisaProdutos(){
    return (EnumPesquisaProdutos)jComboBox1.getSelectedItem();
    }
    public String getPesquisa(){
    return jTPesquisa.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<EnumPesquisaProdutos> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTPesquisa;
    private javax.swing.JTable jTProdutos;
    private javax.swing.JTable jTProdutosSelecionados;
    // End of variables declaration//GEN-END:variables

    public void updateProdutos(List<ProdutoServico> l){
        ((ModeloTabelaProdutos)jTProdutos.getModel()).updateLista(l);
    }
    
    public void updateProdutosSelecionados(List<ProdutoSelecionado> l){
    ((ModeloProdutoSelecionado)jTProdutosSelecionados.getModel()).updateLista(l);
    }
    @Override
    public void finalizar() {
        anterior= null;
        proximo= null;
        encrementarProduto=null;
        decrementarProduto=null;
    }
}
