/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisDeAdicao.painelAdicaoRequisicao;

import com.mycompany.meunegocioprojetointegrador.bd.dominio.DadosDoCliente;
import com.mycompany.meunegocioprojetointegrador.view.IFinalizar;
import com.mycompany.meunegocioprojetointegrador.view.Temas;
import com.mycompany.meunegocioprojetointegrador.view.controles.validador.EnunPesquisaClientes;
import com.mycompany.meunegocioprojetointegrador.view.paineis.Util.PainelLoadBarraCircular;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.ModeloComboboxPesquisaClientes;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.ModeloListaCOntatos;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.PainelParaListaDeClientes;
import com.mycompany.meunegocioprojetointegrador.view.paineis.listas.RencerCellCLiente;
import com.mycompany.meunegocioprojetointegrador.view.paineis.Util.util.PainelComBorda;
import com.mysql.cj.xdevapi.Client;
import java.awt.Dimension;
import java.util.List;
import javax.swing.Box.Filler;
import javax.swing.JOptionPane;
import javax.swing.Popup;
import javax.swing.PopupFactory;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicBorders;

/**
 *
 * @author ramon
 */
public class PainelSelecaoDeCliente extends javax.swing.JPanel implements IFinalizar{
    private DadosDoCliente dadosDoCliente= null;
    private PainelParaListaDeClientes painel= new PainelParaListaDeClientes();
    private Runnable cancelar;
    private Runnable proximo;
    private Runnable pesquisaClientes;
    private Runnable adicionarCliente;
    private UpdateCliente updateCliente;
    /**
     * Creates new form PainelSelecaoDeCliente
     */
    public PainelSelecaoDeCliente(Runnable cancelar,
                                  Runnable proximo,
                                  Runnable pesquisaClientes,
                                  Runnable adicionarCliente,
                                  UpdateCliente upadCliente) {
        this.cancelar=cancelar;
        this.proximo=proximo;
        this.pesquisaClientes=pesquisaClientes;
        this.adicionarCliente=adicionarCliente;
        this.updateCliente=upadCliente;
        initComponents();
        jComboBox1.setSelectedIndex(0);
        jList1.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
              if(  e.getValueIsAdjusting()){
               var itemSelecionado =jList1.getSelectedValue();
               System.err.println("item selecionado "+itemSelecionado);
                  setClienteSelecionado(itemSelecionado);
                  upadCliente.update(itemSelecionado);
                  
              }
            }
        
        });
        painel.setMaximumSize(new Dimension(590,80));
        painel.setAlignmentX(0.5f);
        jpPainelClienteSelecionado.add(painel);
        painel.setVisible(false);
        if(dadosDoCliente!=null){
            setClienteSelecionado(dadosDoCliente);
        }
        
        
    }
    
    public void updateLista(List<DadosDoCliente> l){
    ((ModeloListaCOntatos)jList1.getModel()).adicionarLista(l);
    }
    public void setClienteSelecionado(DadosDoCliente dadosDoCliente){
        if(dadosDoCliente!=null){ 
        this.dadosDoCliente=dadosDoCliente;
         painel.lDoc.setText(dadosDoCliente.getCliente().getCpf());
         painel.lNome.setText(dadosDoCliente.getCliente().getNome());
         painel.lTelefone.setText(dadosDoCliente.getTelefones().getFirst().getTelefone());
         var inicial=dadosDoCliente.getCliente().getNome().charAt(0);
         painel.setIniciais(inicial+"");
         painel.repaint();
         painel.setVisible(true);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTPesquisa = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jComboBox1 = new javax.swing.JComboBox<>();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jpPainelClienteSelecionado = new PainelComBorda();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton4 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 900));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setAlignmentX(0.5F);
        jPanel4.setMaximumSize(new java.awt.Dimension(600, 800));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jPanel4.add(filler2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Selecao de Clientes");
        jPanel4.add(jLabel1);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 60));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jTPesquisa.setMaximumSize(new java.awt.Dimension(300, 22));
        jPanel1.add(jTPesquisa);
        jPanel1.add(filler1);

        jComboBox1.setModel(new ModeloComboboxPesquisaClientes()
        );
        jComboBox1.setLightWeightPopupEnabled(false);
        jComboBox1.setMaximumSize(new java.awt.Dimension(100, 22));
        jComboBox1.setMinimumSize(new java.awt.Dimension(100, 22));
        jComboBox1.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel1.add(jComboBox1);
        jPanel1.add(filler6);

        jButton1.setBackground(Temas.backgraundBotoes);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(23, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jPanel4.add(jPanel1);

        jButton2.setBackground(Temas.backgraundBotoes);
        jButton2.setForeground(Temas.foregraundBotoes);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jButton2.setText("Adicionar");
        jButton2.setMaximumSize(new java.awt.Dimension(102, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jPanel4.add(filler4);

        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(600, 200));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(600, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 200));
        jList1.setCellRenderer(new RencerCellCLiente());

        jList1.setModel(new ModeloListaCOntatos()
        );
        jScrollPane1.setViewportView(jList1);

        jPanel4.add(jScrollPane1);
        jPanel4.add(filler3);

        jpPainelClienteSelecionado.setAlignmentX(0.0F);
        jpPainelClienteSelecionado.setMaximumSize(new java.awt.Dimension(600, 120));
        jpPainelClienteSelecionado.setMinimumSize(new java.awt.Dimension(600, 120));
        jpPainelClienteSelecionado.setPreferredSize(new java.awt.Dimension(600, 120));
        jpPainelClienteSelecionado.setLayout(new javax.swing.BoxLayout(jpPainelClienteSelecionado, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setText("Cliente Selecionado");
        jLabel2.setAlignmentX(0.5F);
        jpPainelClienteSelecionado.add(jLabel2);

        jPanel4.add(jpPainelClienteSelecionado);

        jPanel3.setAlignmentX(0.0F);
        jPanel3.setMaximumSize(new java.awt.Dimension(600, 60));
        jPanel3.setMinimumSize(new java.awt.Dimension(600, 60));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 60));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jButton3.setBackground(Temas.backgraundBotoes);
        jButton3.setForeground(Temas.foregraundBotoes);
        jButton3.setText("Cancelar");
        jButton3.setMaximumSize(new java.awt.Dimension(102, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(102, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jPanel3.add(filler7);
        jPanel3.add(filler8);

        jButton4.setBackground(Temas.backgraundBotoes);
        jButton4.setForeground(Temas.foregraundBotoes);
        jButton4.setText("Proximo");
        jButton4.setMaximumSize(new java.awt.Dimension(102, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(102, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(102, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jPanel4.add(jPanel3);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cancelar.run();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(dadosDoCliente==null){
        JOptionPane.showMessageDialog(this,"Nenhum cliente foi selecionado");
        return;
        }
        
        proximo.run();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pesquisaClientes.run();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.adicionarCliente.run();
    }//GEN-LAST:event_jButton2ActionPerformed

    public boolean checarComboBox(){
    var item =(EnunPesquisaClientes) jComboBox1.getSelectedItem();
    if(item==null){
        JOptionPane.showMessageDialog(jPanel1,"Nenuma opcao de pesquisa foi escolhida");
        return false;
    }
    return true;
    }
    
    public EnunPesquisaClientes getTipoPesquisa(){
    return (EnunPesquisaClientes) jComboBox1.getSelectedItem();
    }
    
    public DadosDoCliente getDadosDoCliente(){
    return dadosDoCliente;
    }
    
    public String getPesquis(){
    return jTPesquisa.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<EnunPesquisaClientes> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<DadosDoCliente> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTPesquisa;
    private javax.swing.JPanel jpPainelClienteSelecionado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void finalizar() {
       this.cancelar=null;
       this.dadosDoCliente=null;
       this.proximo=null;
       this.painel=null;
    }
    
    public  interface UpdateCliente{
    public void update(DadosDoCliente d);
    }
}
