/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.paineisDeVisualizacao.painelVisualizacaoProdutos;

import com.mycompany.meunegocioprojetointegrador.bd.dominio.ProdutoServico;
import com.mycompany.meunegocioprojetointegrador.view.Temas;
import com.mycompany.meunegocioprojetointegrador.view.controles.ControleVisualizarProdutos;
import com.mycompany.meunegocioprojetointegrador.view.navegacao.GerenciadorDepaineis.Painel;
import com.mycompany.meunegocioprojetointegrador.view.respostaParaView.RespostaDeLoad;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ramon
 */
public class PainelVisualizarProdutos extends Painel {
   
   private  Runnable voutar;
   private  Editar editar;
   
   private ControleVisualizarProdutos controle;
   private boolean editado=false;
    /**
     * Creates new form PainelVisualizarProdutos
     */
    public PainelVisualizarProdutos(ControleVisualizarProdutos controle,Runnable voutar,Editar e) {
        
        this.voutar=voutar;
        editar=e;
        this.controle=controle;
        
        initComponents();
        this.controle.getEstadoProduto().observar((p)->{
        if(p!=null)caregarProdutoServico((ProdutoServico) p);
        },this);
        this.controle.getEstadoLoad().observar((r)->{
        if(r instanceof RespostaDeLoad.OKVasio){}
        if(r instanceof RespostaDeLoad.Load){}
        if(r instanceof RespostaDeLoad.Erro er){
            JOptionPane.showMessageDialog(jPanel1,er.mensagem());
        }
        
        }, this);
        
    }
    public void caregarProdutoServico(ProdutoServico p){
     labelProduto.setText(p.getNome());
     labelProdutoServico.setText(p.isServico()?"Servico":"produto");
     labelDescricoa.setText(p.getDescricao());
     labelEstatus.setText((p.isAtivo())?"Ativo":"Inativo");
     labelPreco.setText(String.format("%.2f",p.getPreco()));
     if(p.isAtivo()){
      jBMudarEstatus.setIcon(new ImageIcon(getClass().getResource("/toggle_on_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png")));
     }else{
     jBMudarEstatus.setIcon(new ImageIcon(getClass().getResource("/toggle_off_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png")));
     }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        labelProduto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        labelProdutoServico = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        labelDescricoa = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        labelEstatus = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        labelPreco = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton6 = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jBMudarEstatus = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setMaximumSize(new java.awt.Dimension(32767, 900));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(filler4);

        jPanel2.setMaximumSize(new java.awt.Dimension(600, 50));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Produto :");
        jPanel2.add(jLabel1);
        jPanel2.add(filler1);

        labelProduto.setText("jLabel2");
        labelProduto.setMaximumSize(new java.awt.Dimension(30000, 20));
        labelProduto.setMinimumSize(new java.awt.Dimension(30000, 20));
        labelProduto.setPreferredSize(new java.awt.Dimension(30000, 20));
        jPanel2.add(labelProduto);

        jPanel1.add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(600, 50));
        jPanel3.setMinimumSize(new java.awt.Dimension(600, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Produto/Servico:");
        jPanel3.add(jLabel3);
        jPanel3.add(filler2);

        labelProdutoServico.setText("jLabel2");
        labelProdutoServico.setMaximumSize(new java.awt.Dimension(30000, 20));
        labelProdutoServico.setMinimumSize(new java.awt.Dimension(30000, 20));
        labelProdutoServico.setPreferredSize(new java.awt.Dimension(30000, 20));
        jPanel3.add(labelProdutoServico);

        jPanel1.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(600, 50));
        jPanel4.setMinimumSize(new java.awt.Dimension(600, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Descricao:");
        jPanel4.add(jLabel5);
        jPanel4.add(filler3);

        labelDescricoa.setText("jLabel2");
        labelDescricoa.setMaximumSize(new java.awt.Dimension(30000, 20));
        labelDescricoa.setMinimumSize(new java.awt.Dimension(30000, 20));
        labelDescricoa.setPreferredSize(new java.awt.Dimension(30000, 20));
        jPanel4.add(labelDescricoa);

        jPanel1.add(jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(600, 50));
        jPanel5.setMinimumSize(new java.awt.Dimension(600, 50));
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Estatus");
        jPanel5.add(jLabel6);
        jPanel5.add(filler5);

        labelEstatus.setText("jLabel2");
        labelEstatus.setMaximumSize(new java.awt.Dimension(30000, 20));
        labelEstatus.setMinimumSize(new java.awt.Dimension(30000, 20));
        labelEstatus.setPreferredSize(new java.awt.Dimension(30000, 20));
        jPanel5.add(labelEstatus);

        jPanel1.add(jPanel5);

        jPanel6.setMaximumSize(new java.awt.Dimension(600, 50));
        jPanel6.setMinimumSize(new java.awt.Dimension(600, 50));
        jPanel6.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Preço:");
        jPanel6.add(jLabel7);
        jPanel6.add(filler6);

        labelPreco.setText("jLabel2");
        labelPreco.setMaximumSize(new java.awt.Dimension(30000, 20));
        labelPreco.setMinimumSize(new java.awt.Dimension(30000, 20));
        labelPreco.setPreferredSize(new java.awt.Dimension(30000, 20));
        jPanel6.add(labelPreco);

        jPanel1.add(jPanel6);

        jPanel9.setMaximumSize(new java.awt.Dimension(600, 60));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jButton4.setBackground(Temas.backgraundBotoes);
        jButton4.setForeground(Temas.foregraundBotoes);
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow_back_23dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton4.setText("voutar");
        jButton4.setMaximumSize(new java.awt.Dimension(126, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4);
        jPanel9.add(filler7);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jButton6.setText("Editar");
        jButton6.setMaximumSize(new java.awt.Dimension(136, 30));
        jButton6.setBackground(Temas.backgraundBotoes);
        jButton6.setForeground(Temas.foregraundBotoes);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton6);
        jPanel9.add(filler8);

        jBMudarEstatus.setForeground(new java.awt.Color(255, 255, 255));
        jBMudarEstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toggle_off_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jBMudarEstatus.setText("Mudar estatus");
        jBMudarEstatus.setMaximumSize(new java.awt.Dimension(150, 30));
        jBMudarEstatus.setMinimumSize(new java.awt.Dimension(150, 30));
        jBMudarEstatus.setPreferredSize(new java.awt.Dimension(150, 30));
        jBMudarEstatus.setBackground(Temas.backgraundBotoes);
        jBMudarEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMudarEstatusActionPerformed(evt);
            }
        });
        jPanel9.add(jBMudarEstatus);

        jPanel1.add(jPanel9);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        voutar.run();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        editado=true;
        editar.editar(controle.getEstadoProduto().getValot()); // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jBMudarEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMudarEstatusActionPerformed
        controle.mudarEstatus();
    }//GEN-LAST:event_jBMudarEstatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JButton jBMudarEstatus;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelDescricoa;
    private javax.swing.JLabel labelEstatus;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelProduto;
    private javax.swing.JLabel labelProdutoServico;
    // End of variables declaration//GEN-END:variables

    
    
public interface Editar{
public void editar(ProdutoServico p);
}



    @Override
    public void finalizar() {
        super.finalizar(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
      editar=null;
      voutar=null;
      controle.finalizar();
      controle=null;
    }

    @Override
    public void iniciar() {
        super.iniciar(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
      if(editado){controle.caregarProduto();editado=false;}
    }


}
