/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.Util;

import com.mycompany.meunegocioprojetointegrador.view.Temas;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author ramon
 */
public class Interuptor extends javax.swing.JPanel {
    private boolean selecionado=false;
    private boolean clicadao=false;
    private Color cor= Temas.backgraundBotoes;
    private long timpo=0l;
    private Timer timer;
    private int inicio=0;
    private int centro;
    private Color focoFlatlaf;
    
    
    /**
     * Creates new form Interuptor
     */
    public Interuptor() {
        initComponents();
        setFocusable(true);
        focoFlatlaf=UIManager.getColor("Component.focusColor");
        System.out.println("cor do flatlaf "+focoFlatlaf );
        this.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent e) {
               if((e.getKeyCode() == KeyEvent.VK_SPACE || e.getKeyCode() == KeyEvent.VK_ENTER)&& hasFocus()) {
               clicadao=true;
               selecionado=!selecionado;
               if(selecionado){
                  centro=getWidth();
                  inicio=0;
                 }else{
                  centro=getWidth();
                  inicio=0;
                 }
               timer.start();}
            }
            
        });
        this.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseReleased(MouseEvent e) {
                timpo=System.currentTimeMillis();
                clicadao=true;
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                var aux=System.currentTimeMillis();
                var acionarAcao=((aux-timpo)<100);
                if(acionarAcao){
                 selecionado=!selecionado;
                 if(selecionado){
                  centro=getWidth();
                  inicio=0;
                 }else{
                  centro=getWidth();
                  inicio=0;
                 }
                 timer.start();
                }
            }
        
        });
        this.addFocusListener(new FocusAdapter(){
            @Override
            public void focusLost(FocusEvent e) {
                repaint(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }

            @Override
            public void focusGained(FocusEvent e) {
               repaint(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }
        
        });
    }

    @Override
    protected void paintComponent(Graphics g) {
       super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
       var largura=this.getWidth();
       var altura =this.getHeight();
       var grafico2d =(Graphics2D)g.create();
       
       
       grafico2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
       grafico2d.setColor(Color.WHITE);
       grafico2d.fillRect(0, 0,largura, altura);
      
       grafico2d.setColor(cor);
       if(!clicadao){
           if(!selecionado){
            inicio=0;
            centro=this.getWidth()/2;
           }else{
            inicio=this.getWidth()/2;
            centro=this.getWidth();
           }
           grafico2d.fillRect(inicio, 0,centro,altura);
       }
       else{ 
           
         grafico2d.fillRect(inicio,0, centro,altura);

           
       } 
       if(hasFocus()){
       grafico2d.setStroke(new BasicStroke(1f,1,1));
       grafico2d.setColor(focoFlatlaf);
       grafico2d.drawRect(1,1,largura-1,altura-1);
       }
       /**/
       grafico2d.dispose();
    }   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void removeNotify() {
        System.out.println("metodo remo notify foi ativado ira destruir o timer");
        if(timer!=null&&timer.isRunning())timer.stop();
        var acoes=timer.getActionListeners();
        for(var a :acoes)timer.removeActionListener(a);
        timer=null;
        super.removeNotify();
    }

    @Override
    public void addNotify() {
        System.out.println("metodo add notify foi ativado ira criar o timer");
        timer=new Timer(100,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               if(selecionado){
                   inicio+=10;
                   if(inicio>(getWidth()/2))inicio=getWidth()/2;
                   repaint();
                   if(inicio==(getWidth()/2))timer.stop();
                   return;
               }
               centro-=10;
               if(centro<=(getWidth()/2))centro=getWidth()/2;
               repaint();
               if(centro==(getWidth()/2))timer.stop();
            }
        });
        super.addNotify();
    }

    public void setSelecao(boolean b){
     
      selecionado=b;
        System.out.println("Valor da selecao e "+b);
      repaint();
     
    }

    public boolean isClicadao() {
        return selecionado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
