/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.meunegocioprojetointegrador.view.paineis.Util;

import com.mycompany.meunegocioprojetointegrador.view.Temas;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LinearGradientPaint;
import java.awt.RenderingHints;
import java.awt.Stroke;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.TimerTask;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author ramon
 */
public class PainelLoadBarraCircular extends javax.swing.JPanel {
    private Color cor =Temas.backgraundBotoes;
    private Color corFundo=UIManager.getColor("Panel.background");
    private LinearGradientPaint gradiente;
    private int inicioDoAngulo=0;
    private int anguloFinal=0;
    private Timer timerAnimacao;
    private EstadoDaAnimacao estado=EstadoDaAnimacao.cresendo;
    private int larguraDaLinha=3;
    /**
     * Creates new form PainelLoadBarraCircular
     */
    public PainelLoadBarraCircular() {
        initComponents();
        iniciarGradiente();
    }
    public PainelLoadBarraCircular(Color cor,Color fundo) {
        this.cor=cor;
        this.corFundo=fundo;
        initComponents();
        iniciarGradiente();
    }

    @Override
    public void removeNotify() {
        if(timerAnimacao!=null){
         timerAnimacao.stop();
         timerAnimacao=null;
         }
        super.removeNotify();
       }

    @Override
    public void addNotify() {
        super.addNotify(); 
        if(timerAnimacao==null){
           
          var update =((int)360/(1000/16));
            System.out.println("valor de  update "+update);
         timerAnimacao= new Timer(16,new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
             if(estado==EstadoDaAnimacao.cresendo){
             anguloFinal+=update;
             if(anguloFinal>=360){
             anguloFinal=360;
             estado=EstadoDaAnimacao.Diminuindo;
             }
             repaint();
             return;
             }
             inicioDoAngulo+=update;
             anguloFinal-=update;
             if(inicioDoAngulo>=360){
              inicioDoAngulo=0;
              anguloFinal=0;
              estado=EstadoDaAnimacao.cresendo;
             }
             repaint();
             }
         });
         timerAnimacao.start();
        }
    }
    
    
    
    private void iniciarGradiente(){
     gradiente= new LinearGradientPaint(6,
                                  5,
                                    this.getWidth(),
                                    this.getHeight(),
                                        new float[]{0.1f,0.9f} ,
                                        new Color[]{corFundo,cor});
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        var grafico2D =(Graphics2D)g.create();
        var tamanhoMinimo=Math.min(this.getHeight(),this.getWidth()-(larguraDaLinha*2));
        var posicaoX =(this.getWidth()-tamanhoMinimo)/2;
        var posicaoY =(this.getHeight()-tamanhoMinimo)/2;
        grafico2D.setStroke(new BasicStroke(larguraDaLinha,BasicStroke.CAP_ROUND,BasicStroke.JOIN_ROUND));
        grafico2D.setColor(cor);
        grafico2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
        grafico2D.drawArc(posicaoX, posicaoY,tamanhoMinimo,tamanhoMinimo,inicioDoAngulo,anguloFinal);
        grafico2D.dispose();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private enum EstadoDaAnimacao{
     Diminuindo,cresendo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
